import { randomUUID } from 'crypto';
import {
  FamilyDungeonAdventure,
  FamilyDungeonScene,
  FamilyDungeonAction,
} from '../server/models/index.js';

const ADVENTURES = [
  {
    code: 'covil_goblin_poeira',
    title: 'O Covil do Goblin da Poeira',
    description: 'Um redemoinho de sujeira e bagunça tomou conta do sótão ancestral da mansão. O Goblin da Poeira escondeu pertences valiosos entre pilhas de desordem. Suas escolhas definirão caminhos completamente diferentes pela masmorra!',
    cover_icon: '🧹',
    difficulty_level: 'EASY',
    energy_cost: 5,
    base_gold_reward: 45,
    base_xp_reward: 70,
    scenes: [
      {
        step_order: 1,
        scene_code: 'sotao_entrada',
        title: 'A Porta Misteriosa do Sótão',
        narrative_text: 'Você chega diante da imponente porta de madeira reforçada que dá acesso ao sótão esquecido. Ela está trancada e barulhos abafados de sussurros vêm do interior. Como você decide superá-la?',
        scene_icon: '🚪',
        is_final_scene: false,
        actions: [
          {
            action_number: 1,
            title: 'Físico: Dar um potente chute na porta para arrombá-la',
            attribute_code: 'str',
            difficulty_dc: 10,
            success_text: 'BOOM! O chute despedaça o trinco com violência heróica! A porta se escancara e você invade a sala num estrondo épico!',
            failure_text: 'O chute bate em cheio na viga de ferro com um baque surdo! A porta não abre e você torce o pé dolorosamente (-10 HP)!',
            failure_damage: 10,
            bonus_gold: 5,
            success_scene_code: 'sala_arrombada',
            failure_scene_code: 'porta_travada_alerta',
          },
          {
            action_number: 2,
            title: 'Destreza: Utilizar ferramentas de gazua para arrombar em silêncio',
            attribute_code: 'agi',
            difficulty_dc: 10,
            success_text: 'Click! Com mãos precisas e ágeis, os pinos de bronze cedem e o trinco desliza sem nenhum rangido!',
            failure_text: 'Crack! A gazua entorta e quebra no interior do miolo, trancando a fechadura e machucando seus dedos (-10 HP)!',
            failure_damage: 10,
            bonus_gold: 5,
            success_scene_code: 'sala_infiltrada',
            failure_scene_code: 'fechadura_quebrada',
          },
          {
            action_number: 3,
            title: 'Inteligência: Procurar uma chave escondida ao redor da região',
            attribute_code: 'int',
            difficulty_dc: 9,
            success_text: 'Investigando com olhar atento o batente superior, seus dedos encontram a Chave de Latão Secreta!',
            failure_text: 'Ao mexer numa tábua solta, você esbarra num gatilho oculto que dispara uma nuvem de pó nos seus olhos (-10 HP)!',
            failure_damage: 10,
            bonus_gold: 8,
            success_scene_code: 'sala_chave_mestra',
            failure_scene_code: 'armadilha_poeira',
          },
        ],
      },
      {
        step_order: 2,
        scene_code: 'sala_arrombada',
        title: 'Invasão Triunfal: A Sala Assustada',
        narrative_text: 'A porta se estilhaça e você entra com ímpeto na sala! Várias sombras de poeira e servos goblins param imediatamente o que estavam fazendo, boquiabertos e com os olhos arregalados encarando você em choque!',
        scene_icon: '💥',
        is_final_scene: false,
        actions: [
          {
            action_number: 1,
            title: 'Rugir um grito de guerra intimidador para paralisá-los de medo',
            attribute_code: 'cha',
            difficulty_dc: 10,
            success_text: 'Sua presença majestosa e voz trovejante faz os monstrinhos soltarem tudo e fugirem apavorados!',
            failure_text: 'O grito sai desafinado e as criaturas percebem sua hesitação, jogando cinzas quentes em você (-10 HP)!',
            failure_damage: 10,
            bonus_gold: 8,
            success_scene_code: 'duelo_goblin',
            failure_scene_code: 'piso_brinquedos',
          },
          {
            action_number: 2,
            title: 'Arremessar seu escudo como um bumerangue contra o grupo',
            attribute_code: 'str',
            difficulty_dc: 11,
            success_text: 'O escudo bate em cadeia e derruba todos os capangas, limpando o caminho direto para o chefe!',
            failure_text: 'O escudo bate na parede e ricocheteia raspando no seu braço (-10 HP)!',
            failure_damage: 10,
            bonus_gold: 7,
            success_scene_code: 'duelo_goblin',
            failure_scene_code: 'nevoa_poeira',
          },
          {
            action_number: 3,
            title: 'Aproveitar o choque geral e disparar em velocidade heróica',
            attribute_code: 'agi',
            difficulty_dc: 10,
            success_text: 'Você corta o salão em zigue-zague veloz antes que qualquer um deles consiga reagir!',
            failure_text: 'Você tropeça numa vassoura velha caída no chão durante a corrida rápida (-10 HP)!',
            failure_damage: 10,
            bonus_gold: 6,
            success_scene_code: 'duelo_goblin',
            failure_scene_code: 'piso_brinquedos',
          },
        ],
      },
      {
        step_order: 2,
        scene_code: 'porta_travada_alerta',
        title: 'Alarme Soado: O Sótão em Alerta',
        narrative_text: 'A porta permaneceu imóvel e o estrondo alertou os habitantes do covil. Do outro lado da fresta, você escuta passos apressados e uma voz estridente sussurrando: "Tem alguém tentando invadir! Preparem as armadilhas de poeira!". Você precisa agir rápido!',
        scene_icon: '🚨',
        is_final_scene: false,
        actions: [
          {
            action_number: 1,
            title: 'Utilizar uma viga pesada de madeira como alavanca e forçar a fresta',
            attribute_code: 'str',
            difficulty_dc: 11,
            success_text: 'Com um esforço muscular titânico, a alavanca estoura a barra de contenção e a porta cede!',
            failure_text: 'A viga racha ao meio sob a pressão, estilhaçando madeira no seu peitoral (-12 HP)!',
            failure_damage: 12,
            bonus_gold: 6,
            success_scene_code: 'nevoa_poeira',
            failure_scene_code: 'piso_brinquedos',
          },
          {
            action_number: 2,
            title: 'Tentar se esgueirar ágil por um duto de ventilação no teto',
            attribute_code: 'agi',
            difficulty_dc: 11,
            success_text: 'Você pula na viga superior, remove a grade do duto e desce silenciosamente atrás das linhas inimigas!',
            failure_text: 'A grade de metal se solta de mau jeito e despenca na sua cabeça (-12 HP)!',
            failure_damage: 12,
            bonus_gold: 7,
            success_scene_code: 'sala_infiltrada',
            failure_scene_code: 'nevoa_poeira',
          },
          {
            action_number: 3,
            title: 'Fingir uma voz amiga dizendo ser o entregador de suprimentos',
            attribute_code: 'cha',
            difficulty_dc: 10,
            success_text: 'Enganados pela sua encenação, os goblins abrem o ferrolho curiosos e caem na sua armadilha!',
            failure_text: 'Eles reconhecem o truque e despejam água com sabão escorregadio pela fresta (-12 HP)!',
            failure_damage: 12,
            bonus_gold: 8,
            success_scene_code: 'sala_arrombada',
            failure_scene_code: 'piso_brinquedos',
          },
        ],
      },
      {
        step_order: 2,
        scene_code: 'sala_infiltrada',
        title: 'Infiltração Furtiva: Posição de Emboscada',
        narrative_text: 'A porta destravou sem ruído. Você entra como uma sombra escorregadia no sótão escuro. Os goblins estão concentrados empilhando caixas velhas e nem notaram sua presença!',
        scene_icon: '🕵️',
        is_final_scene: false,
        actions: [
          {
            action_number: 1,
            title: 'Desarmar furtivamente as linhas de armadilhas antes de avançar',
            attribute_code: 'agi',
            difficulty_dc: 10,
            success_text: 'Seus passos de pluma cortam os fios de alarme um a um. O caminho está seguro!',
            failure_text: 'Seu cotovelo encosta num sino de bronze que emite uma badalada estridente (-10 HP)!',
            failure_damage: 10,
            bonus_gold: 8,
            success_scene_code: 'duelo_goblin',
            failure_scene_code: 'piso_brinquedos',
          },
          {
            action_number: 2,
            title: 'Lançar um feitiço de luz ofuscante para desorientar as criaturas',
            attribute_code: 'int',
            difficulty_dc: 10,
            success_text: 'Um clarão mágico irrompe no sótão, cegando os goblins e permitindo sua aproximação decisiva!',
            failure_text: 'O feitiço faísca na sua mão e queima as pontas dos seus dedos (-10 HP)!',
            failure_damage: 10,
            bonus_gold: 9,
            success_scene_code: 'duelo_goblin',
            failure_scene_code: 'nevoa_poeira',
          },
          {
            action_number: 3,
            title: 'Golpear o baú principal de surpresa com sua arma',
            attribute_code: 'str',
            difficulty_dc: 11,
            success_text: 'O ataque certeiro quebra a fortaleza de bagunça e derruba as sentinelas em pânico!',
            failure_text: 'Você erra o golpe nas sombras e acerta um cano de ferro que estremece seus braços (-10 HP)!',
            failure_damage: 10,
            bonus_gold: 7,
            success_scene_code: 'duelo_goblin',
            failure_scene_code: 'nevoa_poeira',
          },
        ],
      },
      {
        step_order: 2,
        scene_code: 'fechadura_quebrada',
        title: 'Tranca Danificada: O Desafio dos Ecos',
        narrative_text: 'A gazua se partiu no miolo e a fechadura travou de vez! Pequenos sinos de metal presos na porta badalam freneticamente, e um jato de fumaça acre começa a vazar pela fechadura emperrada!',
        scene_icon: '🔒',
        is_final_scene: false,
        actions: [
          {
            action_number: 1,
            title: 'Arremeter com ombro heróico e romper o batente fragilizado',
            attribute_code: 'con',
            difficulty_dc: 11,
            success_text: 'Com a rigidez do seu escudo de proteção, a madeira estala e você atravessa o portal!',
            failure_text: 'O impacto afeta seu ombro e você recua dolorido com a porta intacta (-12 HP)!',
            failure_damage: 12,
            bonus_gold: 6,
            success_scene_code: 'piso_brinquedos',
            failure_scene_code: 'nevoa_poeira',
          },
          {
            action_number: 2,
            title: 'Desmontar as dobradiças externas usando raciocínio lógico',
            attribute_code: 'int',
            difficulty_dc: 10,
            success_text: 'Você percebe que os pinos da dobradiça estão expostos e os remove com maestria cirúrgica!',
            failure_text: 'O pino de ferro escapa e prende seu dedo na calha enferrujada (-12 HP)!',
            failure_damage: 12,
            bonus_gold: 8,
            success_scene_code: 'sala_infiltrada',
            failure_scene_code: 'nevoa_poeira',
          },
          {
            action_number: 3,
            title: 'Contar com a sorte e chutar a maçaneta no ângulo exato do mecanismo',
            attribute_code: 'luk',
            difficulty_dc: 11,
            success_text: 'Que pontaria genial! O pedaço de gazua solta a engrenagem e a porta abre com um estalo!',
            failure_text: 'O chute rebate e nada acontece exceto mais dor no seu tornozelo (-12 HP)!',
            failure_damage: 12,
            bonus_gold: 7,
            success_scene_code: 'sala_arrombada',
            failure_scene_code: 'piso_brinquedos',
          },
        ],
      },
      {
        step_order: 2,
        scene_code: 'sala_chave_mestra',
        title: 'O Corredor Secreto da Chave Dourada',
        narrative_text: 'A chave dourada girou como manteiga! Em vez de entrar no corredor barulhento, você descobriu um atalho secreto pelas paredes do sótão, ladeado por estantes de livros e relíquias de família intactas.',
        scene_icon: '🗝️',
        is_final_scene: false,
        actions: [
          {
            action_number: 1,
            title: 'Consultar os mapas do sótão antigos para neutralizar as armadilhas',
            attribute_code: 'int',
            difficulty_dc: 10,
            success_text: 'Com os planos na mente, você desativa os mecanismos do sótão e segue em linha reta ao mestre!',
            failure_text: 'Um erro de leitura aciona uma estante que cai na sua direção de surpresa (-10 HP)!',
            failure_damage: 10,
            bonus_gold: 10,
            success_scene_code: 'duelo_goblin',
            failure_scene_code: 'nevoa_poeira',
          },
          {
            action_number: 2,
            title: 'Invocar o apoio dos guardiões familiares para iluminar o caminho',
            attribute_code: 'cha',
            difficulty_dc: 10,
            success_text: 'Uma aura de bravura protege seus passos e as sombras de desordem se dissolvem!',
            failure_text: 'Uma lufada de vento gélido apaga suas tochas e gela seu peito (-10 HP)!',
            failure_damage: 10,
            bonus_gold: 8,
            success_scene_code: 'duelo_goblin',
            failure_scene_code: 'piso_brinquedos',
          },
          {
            action_number: 3,
            title: 'Avançar com passos calculados e recolher moedas antigas no chão',
            attribute_code: 'luk',
            difficulty_dc: 10,
            success_text: 'Além de passar incólume pelas defesas, você encontra um punhado de moedas de ouro reluzentes!',
            failure_text: 'Você pisa num assoalho falso e sua perna cai num buraco até o quadril (-10 HP)!',
            failure_damage: 10,
            bonus_gold: 12,
            success_scene_code: 'duelo_goblin',
            failure_scene_code: 'piso_brinquedos',
          },
        ],
      },
      {
        step_order: 2,
        scene_code: 'armadilha_poeira',
        title: 'A Nuvem Asfixiante de Poeira',
        narrative_text: 'O pó cinzento entrou em seus olhos e pulmões! Uma cortina de poeira mágica obscurece tudo ao redor, e risadinhas estridentes zombam da sua tosse descontrolada.',
        scene_icon: '🌫️',
        is_final_scene: false,
        actions: [
          {
            action_number: 1,
            title: 'Resistir ao sufocamento e avançar às cegas com o peito aberto',
            attribute_code: 'con',
            difficulty_dc: 11,
            success_text: 'Pulmões heróicos! Você ignora a ardência, rompe a fumaça e ganha terreno limpo!',
            failure_text: 'A tosse violenta dobra seus joelhos e o ar rarefeito drena sua força (-12 HP)!',
            failure_damage: 12,
            bonus_gold: 6,
            success_scene_code: 'piso_brinquedos',
            failure_scene_code: 'nevoa_poeira',
          },
          {
            action_number: 2,
            title: 'Usar sua capa para filtrar o ar e correr no sentido do vento',
            attribute_code: 'agi',
            difficulty_dc: 10,
            success_text: 'Com reflexo veloz, você protege a respiração e encontra a saída da nuvem sem percalços!',
            failure_text: 'A capa se enrola no seu pescoço e você tropeça num baú de ferro (-12 HP)!',
            failure_damage: 12,
            bonus_gold: 7,
            success_scene_code: 'sala_infiltrada',
            failure_scene_code: 'nevoa_poeira',
          },
          {
            action_number: 3,
            title: 'Bater o cabo da espada para assustar as sombras com eco estrondoso',
            attribute_code: 'str',
            difficulty_dc: 11,
            success_text: 'As vibrações sonoras dispersam a poeira e põem as criaturinhas para correr!',
            failure_text: 'O golpe na pedra machuca seu pulso e atrai mais poeira mágica (-12 HP)!',
            failure_damage: 12,
            bonus_gold: 6,
            success_scene_code: 'sala_arrombada',
            failure_scene_code: 'piso_brinquedos',
          },
        ],
      },
      {
        step_order: 3,
        scene_code: 'nevoa_poeira',
        title: 'O Salão do Vórtice Sombrio',
        narrative_text: 'Um redemoinho cinzento gira furiosamente no centro do cômodo. Objetos esquecidos flutuam no vórtice, ameaçando atingir quem se aproxima!',
        scene_icon: '🌪️',
        is_final_scene: false,
        actions: [
          {
            action_number: 1,
            title: 'Marchar contra o vendaval com determinação inabalável',
            attribute_code: 'con',
            difficulty_dc: 11,
            success_text: 'Sua firmeza inquebrável corta o vórtice ao meio! A tempestade se dissipa!',
            failure_text: 'Um livro antigo voa em alta velocidade e acerta seu peito com força (-12 HP)!',
            failure_damage: 12,
            bonus_gold: 7,
            success_scene_code: 'duelo_goblin',
            failure_scene_code: 'piso_brinquedos',
          },
          {
            action_number: 2,
            title: 'Esquivar-se agilmente dos destroços giratórios',
            attribute_code: 'agi',
            difficulty_dc: 11,
            success_text: 'Acrobacias perfeitas! Você se desvia de cadeiras e caixas no ar e chega ao centro!',
            failure_text: 'Um cabide de madeira atinge sua perna e rasga sua calça de armadura (-12 HP)!',
            failure_damage: 12,
            bonus_gold: 7,
            success_scene_code: 'duelo_goblin',
            failure_scene_code: 'piso_brinquedos',
          },
          {
            action_number: 3,
            title: 'Entoar o lema de ordem da família para acalmar a magia',
            attribute_code: 'cha',
            difficulty_dc: 10,
            success_text: 'O poder das suas palavras harmoniosas faz a desordem mágica desabar no chão inerte!',
            failure_text: 'O vento engole suas palavras e uma rajada sufocante entra em sua garganta (-12 HP)!',
            failure_damage: 12,
            bonus_gold: 8,
            success_scene_code: 'duelo_goblin',
            failure_scene_code: 'piso_brinquedos',
          },
        ],
      },
      {
        step_order: 3,
        scene_code: 'piso_brinquedos',
        title: 'O Campo de Armadilhas Pontiagudas',
        narrative_text: 'O piso foi semeado com blocos triangulares pontiagudos, brinquedos de ponta e peças afiadas. Pisar em falso aqui é garantia de dor aguda e perda de fôlego!',
        scene_icon: '🧩',
        is_final_scene: false,
        actions: [
          {
            action_number: 1,
            title: 'Saltar de viga em viga pelo madeiramento do teto',
            attribute_code: 'agi',
            difficulty_dc: 11,
            success_text: 'Você pula com leveza felina entre os caibros e aterrissa do outro lado sem tocar no piso!',
            failure_text: 'Seu pé escorrega e você aterrissa em cheio sobre um bloco pontiagudo de quina viva (-12 HP)!',
            failure_damage: 12,
            bonus_gold: 8,
            success_scene_code: 'duelo_goblin',
            failure_scene_code: 'duelo_goblin',
          },
          {
            action_number: 2,
            title: 'Traçar uma rota geométrica segura pelas lacunas do assoalho',
            attribute_code: 'int',
            difficulty_dc: 10,
            success_text: 'Com raciocínio tático impecável, você caminha como um mestre de xadrez sem encostar em nada!',
            failure_text: 'Uma rodinha de patins solta faz seu calcanhar deslizar bruscamente (-12 HP)!',
            failure_damage: 12,
            bonus_gold: 8,
            success_scene_code: 'duelo_goblin',
            failure_scene_code: 'duelo_goblin',
          },
          {
            action_number: 3,
            title: 'Puxar uma pesada passadeira de veludo para forrar o chão',
            attribute_code: 'str',
            difficulty_dc: 11,
            success_text: 'Com força muscular exemplar, você estica o tapete cobrindo todas as armadilhas!',
            failure_text: 'O tapete rasga e uma tachinha afiada fura a sola de couro de sua bota (-12 HP)!',
            failure_damage: 12,
            bonus_gold: 7,
            success_scene_code: 'duelo_goblin',
            failure_scene_code: 'duelo_goblin',
          },
        ],
      },
      {
        step_order: 4,
        scene_code: 'duelo_goblin',
        title: 'O Duelo contra o Goblin da Poeira',
        narrative_text: 'Empoleirado em uma montanha de malas antigas, surge o chefe do covil: o Goblin da Poeira! Olhos amarelos zombeteiros, ele brande um espanador negro que dispara lufadas de fumaça cinzenta. "Ninguém limpa o meu reino da bagunça!", berra ele!',
        scene_icon: '👾',
        is_final_scene: false,
        actions: [
          {
            action_number: 1,
            title: 'Investir com corte firme e decepar o espanador sombrio',
            attribute_code: 'str',
            difficulty_dc: 12,
            success_text: 'Seu golpe certeiro corta o cabo do espanador mágico! O goblin cai de costas em desespero!',
            failure_text: 'O monstro salta ágil e chicoteia seu peito com pó cáustico (-14 HP)!',
            failure_damage: 14,
            bonus_gold: 10,
            success_scene_code: 'bau_tesouro_goblin',
            failure_scene_code: 'bau_tesouro_goblin',
          },
          {
            action_number: 2,
            title: 'Efetuar rolamento rápido e encurralá-lo pelas costas',
            attribute_code: 'agi',
            difficulty_dc: 11,
            success_text: 'Em fração de segundo você ressurge atrás da pilha de malas e prende o goblin sob sua capa!',
            failure_text: 'Ele percebe seu movimento e empurra uma pilha de caixas nas suas costelas (-14 HP)!',
            failure_damage: 14,
            bonus_gold: 9,
            success_scene_code: 'bau_tesouro_goblin',
            failure_scene_code: 'bau_tesouro_goblin',
          },
          {
            action_number: 3,
            title: 'Proclamar a Ordem da Casa: "Aqui a Preguiça Não Tem Vez!"',
            attribute_code: 'cha',
            difficulty_dc: 11,
            success_text: 'A energia moral da sua voz quebra a maldição do monstro! Ele encolhe e foge pelo telhado!',
            failure_text: 'Ele gargalha da sua ordem e lança uma onda de choque de poeira sufocante (-14 HP)!',
            failure_damage: 14,
            bonus_gold: 10,
            success_scene_code: 'bau_tesouro_goblin',
            failure_scene_code: 'bau_tesouro_goblin',
          },
        ],
      },
      {
        step_order: 5,
        scene_code: 'bau_tesouro_goblin',
        title: 'A Câmara do Baú de Pinho Dourado',
        narrative_text: 'Com a desordem vencida, raios de sol atravessam a clarabóia do sótão iluminando um magnífico Baú de Pinho talhado com runas de ouro. O baú contém as relíquias do lar resgatadas da escuridão!',
        scene_icon: '👑',
        is_final_scene: true,
        actions: [
          {
            action_number: 1,
            title: 'Decifrar as três runas do cadeado ancestral',
            attribute_code: 'int',
            difficulty_dc: 10,
            success_text: 'As runas brilham em azul safira! O ferrolho desliza suavemente com um tilintar harmonioso!',
            failure_text: 'Um choque mágico menor atinge suas pontas dos dedos, mas a fechadura cede (-8 HP)!',
            failure_damage: 8,
            bonus_gold: 15,
            success_scene_code: null,
            failure_scene_code: null,
          },
          {
            action_number: 2,
            title: 'Utilizar a Gazua da Sorte girando os pinos de metal',
            attribute_code: 'luk',
            difficulty_dc: 9,
            success_text: 'Click! Um estalo triunfal ecoa no sótão e a tampa se abre de par em par com brilho dourado!',
            failure_text: 'A gazua entorta, forçando você a puxar a trava na marra com um arranhão no braço (-8 HP)!',
            failure_damage: 8,
            bonus_gold: 15,
            success_scene_code: null,
            failure_scene_code: null,
          },
          {
            action_number: 3,
            title: 'Erguer a tampa de carvalho maciço com vigor heróico',
            attribute_code: 'con',
            difficulty_dc: 10,
            success_text: 'Seus músculos firmes sustentam o peso da tampa de chumbo e revelam o fabuloso tesouro!',
            failure_text: 'A tampa é incrivelmente pesada e machuca sua mão antes de abrir completamente (-8 HP)!',
            failure_damage: 8,
            bonus_gold: 12,
            success_scene_code: null,
            failure_scene_code: null,
          },
        ],
      },
    ],
  },
  {
    code: 'torre_devorador_paginas',
    title: 'A Torre do Devorador de Páginas',
    description: 'No alto da biblioteca flutuante do reino, o Devorador de Páginas está roendo os segredos dos livros de conhecimento e lições escolares. Decifre os enigmas arcanos, prove sua inteligência e salve a sabedoria da família!',
    cover_icon: '📚',
    difficulty_level: 'MEDIUM',
    energy_cost: 5,
    base_gold_reward: 60,
    base_xp_reward: 90,
    scenes: [
      {
        step_order: 1,
        scene_code: 'portao_biblioteca',
        title: 'O Portal dos Enigmas Gravados',
        narrative_text: 'Você chega diante do enorme portal de bronze da Torre do Saber. Na porta, letras brilhantes formam uma charada: "Quanto mais você tem de mim, menos você vê no escuro. Quem sou eu?". Três fechaduras mágicas aguardam sua resposta.',
        scene_icon: '🚪',
        is_final_scene: false,
        actions: [
          {
            action_number: 1,
            title: 'Responder com convicção: "A Luz!" (Canalizar faísca arcana)',
            attribute_code: 'int',
            difficulty_dc: 11,
            success_text: 'As letras brilham em dourado radiante! A resposta está correta e os pesados ferrolhos se abrem!',
            failure_text: 'Sua voz titubeia na resposta; uma fagulha de rejeição mágica queima sua túnica (-12 HP)!',
            failure_damage: 12,
            bonus_gold: 8,
            success_scene_code: 'escadaria_livros',
            failure_scene_code: 'sala_pergaminhos',
          },
          {
            action_number: 2,
            title: 'Examinar o mecanismo de contrapeso das engrenagens',
            attribute_code: 'agi',
            difficulty_dc: 12,
            success_text: 'Seus dedos rápidos encontram a trava de emergência e destrancam a porta mecanicamente!',
            failure_text: 'Uma das engrenagens range e prende sua luva nas correntes de tração (-12 HP)!',
            failure_damage: 12,
            bonus_gold: 7,
            success_scene_code: 'escadaria_livros',
            failure_scene_code: 'sala_pergaminhos',
          },
          {
            action_number: 3,
            title: 'Forçar as duas batentes de bronze com ombro firme',
            attribute_code: 'str',
            difficulty_dc: 13,
            success_text: 'Com um urro de determinação, você supera a trava arcaica na força bruta!',
            failure_text: 'O bronze encantado repele seu impacto com uma onda de choque reverberante (-12 HP)!',
            failure_damage: 12,
            bonus_gold: 6,
            success_scene_code: 'escadaria_livros',
            failure_scene_code: 'sala_pergaminhos',
          },
        ],
      },
      {
        step_order: 2,
        scene_code: 'escadaria_livros',
        title: 'A Escadaria dos Tomos Flutuantes',
        narrative_text: 'O interior da torre é um abismo espiral sem chão fixo. Para subir, você precisa saltar sobre grossos livros de feitiços que flutuam no ar ao sabor de ventos mágicos inconstantes.',
        scene_icon: '📖',
        is_final_scene: false,
        actions: [
          {
            action_number: 1,
            title: 'Saltar com agilidade e ritmo impecável de capa em capa',
            attribute_code: 'agi',
            difficulty_dc: 12,
            success_text: 'Leve como uma pluma, você corre sobre os livros voadores sem fazê-los oscilar nem um centímetro!',
            failure_text: 'Um tomo fecha de repente! Você perde o equilíbrio e raspa as pernas na beirada de pedra (-14 HP)!',
            failure_damage: 14,
            bonus_gold: 8,
            success_scene_code: 'confronto_devorador',
            failure_scene_code: 'sala_pergaminhos',
          },
          {
            action_number: 2,
            title: 'Ler os títulos em latim para pisar apenas nos livros estáveis',
            attribute_code: 'int',
            difficulty_dc: 11,
            success_text: 'Você nota que os tratados de Astronomia possuem aterrissagem estável e sobe tranquilamente!',
            failure_text: 'Você confunde um tomo de Levitação com um de Queda Livre e despenca alguns metros (-14 HP)!',
            failure_damage: 14,
            bonus_gold: 9,
            success_scene_code: 'confronto_devorador',
            failure_scene_code: 'sala_pergaminhos',
          },
          {
            action_number: 3,
            title: 'Confiar na sorte e saltar com fé no fluxo dos ventos',
            attribute_code: 'luk',
            difficulty_dc: 12,
            success_text: 'Uma brisa repentina ergue um enorme atlas bem sob os seus pés, levando você ao topo!',
            failure_text: 'O vento cessa no momento crucial e você colide contra a coluna central da torre (-14 HP)!',
            failure_damage: 14,
            bonus_gold: 10,
            success_scene_code: 'confronto_devorador',
            failure_scene_code: 'sala_pergaminhos',
          },
        ],
      },
      {
        step_order: 3,
        scene_code: 'sala_pergaminhos',
        title: 'O Labirinto das Letras Vivas',
        narrative_text: 'Você chega a um salão forrado de estantes infinitas. As letras fugiram das páginas e formam enxames de tinta que rodopiam como vespas. Quem for atingido esquece o que acabou de estudar!',
        scene_icon: '📜',
        is_final_scene: false,
        actions: [
          {
            action_number: 1,
            title: 'Conjurar um escudo de foco e concentração inabalável',
            attribute_code: 'con',
            difficulty_dc: 12,
            success_text: 'Sua mente disciplinada repele o enxame de dispersão! As letras recuam ordenadas!',
            failure_text: 'O turbilhão de letras penetra sua defesa mental, causando tontura e dor de cabeça (-12 HP)!',
            failure_damage: 12,
            bonus_gold: 8,
            success_scene_code: 'confronto_devorador',
            failure_scene_code: 'confronto_devorador',
          },
          {
            action_number: 2,
            title: 'Citar uma poesia harmoniosa para pacificar as palavras',
            attribute_code: 'cha',
            difficulty_dc: 11,
            success_text: 'Ao declamar versos de bravura, as letras se encantam com sua voz e voltam dóceis aos livros!',
            failure_text: 'Você esquece a rima no meio da frase e as palavras rebeldes ferroam seus braços (-12 HP)!',
            failure_damage: 12,
            bonus_gold: 9,
            success_scene_code: 'confronto_devorador',
            failure_scene_code: 'confronto_devorador',
          },
          {
            action_number: 3,
            title: 'Mover-se em zigue-zague veloz esquivando dos pingos de tinta',
            attribute_code: 'agi',
            difficulty_dc: 13,
            success_text: 'Com reflexos de campeão, você dribla cada gota e alcança o outro lado intacto!',
            failure_text: 'Uma saraivada de tinta mágica queima sua bochecha antes de você conseguir se abrigar (-12 HP)!',
            failure_damage: 12,
            bonus_gold: 7,
            success_scene_code: 'confronto_devorador',
            failure_scene_code: 'confronto_devorador',
          },
        ],
      },
      {
        step_order: 4,
        scene_code: 'confronto_devorador',
        title: 'O Duelo contra o Devorador de Páginas',
        narrative_text: 'No topo da cúpula, uma fera monstruosa feita de capas de couro, pergaminhos rasgados e dentes de penas afiadas mastiga enciclopédias: é o Devorador de Páginas! Seus olhos brilham com a preguiça intelectual dos maus estudantes.',
        scene_icon: '🐉',
        is_final_scene: false,
        actions: [
          {
            action_number: 1,
            title: 'Lançar um enigma lógico irrespondível para paralisá-lo',
            attribute_code: 'int',
            difficulty_dc: 12,
            success_text: '"O que tem raiz mas não é árvore, sobe sem andar e cai sem chorar?". O monstro entra em curto-circuito e cai!',
            failure_text: 'O monstro engole seu enigma e sopra uma rajada de páginas em chamas na sua direção (-16 HP)!',
            failure_damage: 16,
            bonus_gold: 12,
            success_scene_code: 'bau_tomo_ancestral',
            failure_scene_code: 'bau_tomo_ancestral',
          },
          {
            action_number: 2,
            title: 'Investir com a espada encantada direto no coração de papiro',
            attribute_code: 'str',
            difficulty_dc: 13,
            success_text: 'Seu corte heroico perfura o núcleo arcano da criatura, libertando todas as letras aprisionadas!',
            failure_text: 'A mandíbula de madeira do monstro golpeia seu escudo com violência estarrecedora (-16 HP)!',
            failure_damage: 16,
            bonus_gold: 10,
            success_scene_code: 'bau_tomo_ancestral',
            failure_scene_code: 'bau_tomo_ancestral',
          },
          {
            action_number: 3,
            title: 'Aproveitar a brecha de ataque e cegá-lo com pó rúnico',
            attribute_code: 'luk',
            difficulty_dc: 12,
            success_text: 'Um golpe de pura sorte acerta os olhos da fera, fazendo-a tropeçar da balaustrada!',
            failure_text: 'O pó sopra de volta nos seus olhos e você recebe uma chicotada de pergaminho (-16 HP)!',
            failure_damage: 16,
            bonus_gold: 11,
            success_scene_code: 'bau_tomo_ancestral',
            failure_scene_code: 'bau_tomo_ancestral',
          },
        ],
      },
      {
        step_order: 5,
        scene_code: 'bau_tomo_ancestral',
        title: 'O Santuário do Baú Arcano',
        narrative_text: 'Com o Devorador derrotado, os tomos da sabedoria voltam às estantes reluzindo em harmonia. No centro do tablado surge o Baú de Safira da Sabedoria, trancado com um segredo matemático reluzente.',
        scene_icon: '💎',
        is_final_scene: true,
        actions: [
          {
            action_number: 1,
            title: 'Resolver a equação rúnica de abertura dos arcanos',
            attribute_code: 'int',
            difficulty_dc: 11,
            success_text: 'Brilhante! A equação se completa e as trancas deslizam com uma chuva de estrelas azuis!',
            failure_text: 'O circuito mágico dá um estalo na sua mão antes de abrir a tampa de cristal (-10 HP)!',
            failure_damage: 10,
            bonus_gold: 20,
            success_scene_code: null,
            failure_scene_code: null,
          },
          {
            action_number: 2,
            title: 'Utilizar sua empatia e espírito de liderança familiar',
            attribute_code: 'cha',
            difficulty_dc: 12,
            success_text: 'O baú reconhece o coração nobre de um herói que valoriza o saber e se abre com deferência!',
            failure_text: 'A energia é intensa demais e descarrega um pulso eletrostático no seu peito (-10 HP)!',
            failure_damage: 10,
            bonus_gold: 18,
            success_scene_code: null,
            failure_scene_code: null,
          },
          {
            action_number: 3,
            title: 'Sustentar os selos de proteção com vigor corporal',
            attribute_code: 'con',
            difficulty_dc: 12,
            success_text: 'Sua resistência heróica dissipa os últimos resquícios da maldição e liberta os tesouros!',
            failure_text: 'O esforço consome suas energias, mas a vitória é consumada com bravura (-10 HP)!',
            failure_damage: 10,
            bonus_gold: 15,
            success_scene_code: null,
            failure_scene_code: null,
          },
        ],
      },
    ],
  },
  {
    code: 'catacumbas_procrastinacao',
    title: 'As Catacumbas da Procrastinação Eterna',
    description: 'Um labirinto subterrâneo onde o tempo passa devagar e uma gosma mágica chamada "Depois Eu Faço" tenta prender os heróis no sono eterno. O Titã da Procrastinação guarda o tesouro dos minutos perdidos!',
    cover_icon: '⏳',
    difficulty_level: 'HARD',
    energy_cost: 5,
    base_gold_reward: 75,
    base_xp_reward: 110,
    scenes: [
      {
        step_order: 1,
        scene_code: 'catacumbas_entrada',
        title: 'O Pântano do "Depois Eu Faço"',
        narrative_text: 'Ao descer os degraus de pedra úmida, seus pés afundam em um lodo roxo pegajoso. Vozes sussurram no ar: "Descanse um pouco... Para que fazer agora? Deixe para amanhã...". Seus membros começam a ficar pesados como chumbo.',
        scene_icon: '🕳️',
        is_final_scene: false,
        actions: [
          {
            action_number: 1,
            title: 'Rejeitar a preguiça com um grito de disciplina e marcha férrea',
            attribute_code: 'con',
            difficulty_dc: 13,
            success_text: 'Sua vontade de aço corta a letargia! Suas pernas rasgam o lodo com vigor inabalável!',
            failure_text: 'A gosma roxa suga sua energia vital, drenando seu vigor com um torpor gélido (-15 HP)!',
            failure_damage: 15,
            bonus_gold: 10,
            success_scene_code: 'pendulos_ampulheta',
            failure_scene_code: 'fosso_desculpas',
          },
          {
            action_number: 2,
            title: 'Saltar sobre pedras secas antes que o lodo se expanda',
            attribute_code: 'agi',
            difficulty_dc: 14,
            success_text: 'Com velocidade supersônica, você quica sobre as pedras pontiagudas sem tocar no pântano!',
            failure_text: 'Uma pedra cede sob sua bota e você afunda até o joelho no pântano sonolento (-15 HP)!',
            failure_damage: 15,
            bonus_gold: 9,
            success_scene_code: 'pendulos_ampulheta',
            failure_scene_code: 'fosso_desculpas',
          },
          {
            action_number: 3,
            title: 'Focar na satisfação do dever cumprido e avançar focado',
            attribute_code: 'int',
            difficulty_dc: 13,
            success_text: 'Sua clareza mental neutraliza o feitiço psicológico da procrastinação com sabedoria!',
            failure_text: 'Pensamentos de adiamento nublam sua mente e você cambaleia no chão úmido (-15 HP)!',
            failure_damage: 15,
            bonus_gold: 11,
            success_scene_code: 'pendulos_ampulheta',
            failure_scene_code: 'fosso_desculpas',
          },
        ],
      },
      {
        step_order: 2,
        scene_code: 'pendulos_ampulheta',
        title: 'O Corredor dos Pêndulos de Areia',
        narrative_text: 'O teto desta galeria estreita é guarnecido por gigantescas lâminas em forma de ampulhetas que oscilam em ritmo descompassado. Um aviso diz: "Quem perde tempo, perde a vida".',
        scene_icon: '⏱️',
        is_final_scene: false,
        actions: [
          {
            action_number: 1,
            title: 'Calcular a cadência dos pêndulos e atravessar no tempo exato',
            attribute_code: 'int',
            difficulty_dc: 13,
            success_text: 'Cronometragem perfeita! Você passa como uma sombra entre as lâminas no milissegundo certo!',
            failure_text: 'O cálculo falha por um instante e a haste de bronze acerta suas costelas (-16 HP)!',
            failure_damage: 16,
            bonus_gold: 12,
            success_scene_code: 'confronto_tita',
            failure_scene_code: 'fosso_desculpas',
          },
          {
            action_number: 2,
            title: 'Usar o escudo pesado para bloquear a lateral de uma lâmina',
            attribute_code: 'str',
            difficulty_dc: 14,
            success_text: 'Com força hercúlea você desvia o pêndulo e abre espaço seguro para passar!',
            failure_text: 'O impacto violento do pêndulo entorta a empunhadura do seu escudo (-16 HP)!',
            failure_damage: 16,
            bonus_gold: 10,
            success_scene_code: 'confronto_tita',
            failure_scene_code: 'fosso_desculpas',
          },
          {
            action_number: 3,
            title: 'Deslizar pelo chão úmido no momento em que as lâminas sobem',
            attribute_code: 'agi',
            difficulty_dc: 14,
            success_text: 'Um slide espetacular rente ao piso de pedra leva você até o outro lado ileso!',
            failure_text: 'O chão áspero segura sua túnica e você raspa o joelho na pedra afiada (-16 HP)!',
            failure_damage: 16,
            bonus_gold: 11,
            success_scene_code: 'confronto_tita',
            failure_scene_code: 'fosso_desculpas',
          },
        ],
      },
      {
        step_order: 3,
        scene_code: 'fosso_desculpas',
        title: 'O Fosso das Desculpas Esfarrapadas',
        narrative_text: 'Você cai em um poço onde ecos de desculpas ressoam infinitamente: "Estou cansado", "Amanhã eu começo", "Hoje não dá tempo". Fantasmas da preguiça puxam sua capa para baixo.',
        scene_icon: '👻',
        is_final_scene: false,
        actions: [
          {
            action_number: 1,
            title: 'Silenciar os ecos com um grito de motivação e dever familiar',
            attribute_code: 'cha',
            difficulty_dc: 13,
            success_text: 'Sua convicção pura faz os fantasmas covardes se calarem e desaparecerem no nada!',
            failure_text: 'As desculpas sussurram na sua orelha e paralisam sua vontade momentaneamente (-15 HP)!',
            failure_damage: 15,
            bonus_gold: 10,
            success_scene_code: 'confronto_tita',
            failure_scene_code: 'confronto_tita',
          },
          {
            action_number: 2,
            title: 'Escalar a parede de rocha íngreme usando a força dos braços',
            attribute_code: 'str',
            difficulty_dc: 14,
            success_text: 'Músculo sobre rocha! Você sobe pelas frestas de pedra como um alpinista de elite!',
            failure_text: 'Uma pedra se desprende e você despenca de volta ao fundo do fosso (-15 HP)!',
            failure_damage: 15,
            bonus_gold: 11,
            success_scene_code: 'confronto_tita',
            failure_scene_code: 'confronto_tita',
          },
          {
            action_number: 3,
            title: 'Confiar na determinação e arremessar um gancho no escuro',
            attribute_code: 'luk',
            difficulty_dc: 13,
            success_text: 'O gancho se prende com firmeza em uma raiz e você sobe triunfante ao piso superior!',
            failure_text: 'O gancho volta solto e acerta seu ombro com o peso do chumbo (-15 HP)!',
            failure_damage: 15,
            bonus_gold: 12,
            success_scene_code: 'confronto_tita',
            failure_scene_code: 'confronto_tita',
          },
        ],
      },
      {
        step_order: 4,
        scene_code: 'confronto_tita',
        title: 'O Confronto com o Titã da Procrastinação',
        narrative_text: 'No salão central, ergue-se uma estátua colossal viva de rocha escura e areia movediça: o Titã da Procrastinação! Ele segura um martelo em formato de ampulheta que esmaga os segundos.',
        scene_icon: '🗿',
        is_final_scene: false,
        actions: [
          {
            action_number: 1,
            title: 'Desferir um golpe demolidor no ponto fraco do peito de rocha',
            attribute_code: 'str',
            difficulty_dc: 14,
            success_text: 'CRASH! Seu golpe despedaça a carcaça de preguiça do monstro, que desaba em pó inofensivo!',
            failure_text: 'O martelo de areia do Titã golpeia o chão e a onda sísmica arremessa você na parede (-18 HP)!',
            failure_damage: 18,
            bonus_gold: 15,
            success_scene_code: 'bau_rubi_tempo',
            failure_scene_code: 'bau_rubi_tempo',
          },
          {
            action_number: 2,
            title: 'Desviar com fintas elétricas e fazê-lo martelar a própria base',
            attribute_code: 'agi',
            difficulty_dc: 14,
            success_text: 'Você esquiva no último segundo! O monstro acerta os próprios joelhos e se desintegra!',
            failure_text: 'A areia mágica prende seus pés e você recebe uma rajada de estilhaços de rocha (-18 HP)!',
            failure_damage: 18,
            bonus_gold: 14,
            success_scene_code: 'bau_rubi_tempo',
            failure_scene_code: 'bau_rubi_tempo',
          },
          {
            action_number: 3,
            title: 'Canalizar a determinação dos deveres cumpridos e dissipar a ilusão',
            attribute_code: 'con',
            difficulty_dc: 13,
            success_text: 'Sua disciplina espiritual brilha como ouro e derrete a forma física do Titã em segundos!',
            failure_text: 'A aura de letargia o envolve e drena seu ar antes de você conseguir se libertar (-18 HP)!',
            failure_damage: 18,
            bonus_gold: 16,
            success_scene_code: 'bau_rubi_tempo',
            failure_scene_code: 'bau_rubi_tempo',
          },
        ],
      },
      {
        step_order: 5,
        scene_code: 'bau_rubi_tempo',
        title: 'A Câmara do Baú de Rubi Cronológico',
        narrative_text: 'O tempo volta a correr com leveza e serenidade. Na ponta de um pedestal de mármore branco surge o lendário Baú de Rubi, que guarda os minutos preciosos devolvidos à sua família!',
        scene_icon: '💎',
        is_final_scene: true,
        actions: [
          {
            action_number: 1,
            title: 'Sincronizar os ponteiros dourados do baú com o ritmo do coração',
            attribute_code: 'con',
            difficulty_dc: 13,
            success_text: 'Harmonia absoluta! As trancas estalam em ritmo perfeito e o baú se abre reluzindo!',
            failure_text: 'Um estalo de mola bate nas suas unhas, mas a tampa finalmente cede (-10 HP)!',
            failure_damage: 10,
            bonus_gold: 25,
            success_scene_code: null,
            failure_scene_code: null,
          },
          {
            action_number: 2,
            title: 'Alinhar as três gemas de rubi que refratam a luz do dia',
            attribute_code: 'int',
            difficulty_dc: 12,
            success_text: 'A luz solar se concentra num raio vermelho intenso que desfaz os lacres de pedra!',
            failure_text: 'O reflexo do laser queima a ponta da sua luva de couro antes de abrir o baú (-10 HP)!',
            failure_damage: 10,
            bonus_gold: 24,
            success_scene_code: null,
            failure_scene_code: null,
          },
          {
            action_number: 3,
            title: 'Apostar na bênção do destino e girar a chave mística',
            attribute_code: 'luk',
            difficulty_dc: 12,
            success_text: 'A sorte dos heróis sorri radiante e o tesouro se revela com abundância régia!',
            failure_text: 'A chave dá um tranco forte no seu punho antes de girar totalmente (-10 HP)!',
            failure_damage: 10,
            bonus_gold: 22,
            success_scene_code: null,
            failure_scene_code: null,
          },
        ],
      },
    ],
  },
];

async function seed() {
  try {
    console.log('🌱 Populando Aventuras em Masmorra com Árvore de Causa e Consequência...');

    for (const advData of ADVENTURES) {
      // 1. Criar ou atualizar a Masmorra
      let adventure = await FamilyDungeonAdventure.findOne({
        where: { code: advData.code },
      });

      if (!adventure) {
        adventure = await FamilyDungeonAdventure.create({
          id: randomUUID().toLowerCase(),
          code: advData.code,
          title: advData.title,
          description: advData.description,
          cover_icon: advData.cover_icon,
          difficulty_level: advData.difficulty_level,
          energy_cost: advData.energy_cost,
          base_gold_reward: advData.base_gold_reward,
          base_xp_reward: advData.base_xp_reward,
          is_active: true,
        });
        console.log(`✨ Masmorra criada: ${advData.title}`);
      } else {
        await adventure.update({
          title: advData.title,
          description: advData.description,
          cover_icon: advData.cover_icon,
          difficulty_level: advData.difficulty_level,
          energy_cost: advData.energy_cost,
          base_gold_reward: advData.base_gold_reward,
          base_xp_reward: advData.base_xp_reward,
          is_active: true,
        });
        console.log(`🔄 Masmorra atualizada: ${advData.title}`);
      }

      // 2. Criar ou atualizar as Cenas
      for (const scnData of advData.scenes) {
        let scene = await FamilyDungeonScene.findOne({
          where: { adventure_id: adventure.id, scene_code: scnData.scene_code },
        });

        if (!scene) {
          scene = await FamilyDungeonScene.create({
            id: randomUUID().toLowerCase(),
            adventure_id: adventure.id,
            step_order: scnData.step_order,
            scene_code: scnData.scene_code,
            title: scnData.title,
            narrative_text: scnData.narrative_text,
            scene_icon: scnData.scene_icon,
            scene_image_url: scnData.scene_image_url || null,
            is_final_scene: scnData.is_final_scene,
          });
        } else {
          await scene.update({
            step_order: scnData.step_order,
            title: scnData.title,
            narrative_text: scnData.narrative_text,
            scene_icon: scnData.scene_icon,
            scene_image_url: scnData.scene_image_url || null,
            is_final_scene: scnData.is_final_scene,
          });
        }

        // 3. Criar ou atualizar as 3 ações com ramificação de causa e consequência
        for (const actData of scnData.actions) {
          let action = await FamilyDungeonAction.findOne({
            where: { scene_id: scene.id, action_number: actData.action_number },
          });

          if (!action) {
            await FamilyDungeonAction.create({
              id: randomUUID().toLowerCase(),
              scene_id: scene.id,
              action_number: actData.action_number,
              title: actData.title,
              attribute_code: actData.attribute_code,
              difficulty_dc: actData.difficulty_dc,
              success_text: actData.success_text,
              failure_text: actData.failure_text,
              failure_damage: actData.failure_damage,
              bonus_gold: actData.bonus_gold,
              success_scene_code: actData.success_scene_code || null,
              failure_scene_code: actData.failure_scene_code || null,
            });
          } else {
            await action.update({
              title: actData.title,
              attribute_code: actData.attribute_code,
              difficulty_dc: actData.difficulty_dc,
              success_text: actData.success_text,
              failure_text: actData.failure_text,
              failure_damage: actData.failure_damage,
              bonus_gold: actData.bonus_gold,
              success_scene_code: actData.success_scene_code || null,
              failure_scene_code: actData.failure_scene_code || null,
            });
          }
        }
      }
    }

    console.log('🎉 Todas as Masmorras e suas cenas ramificadas de causa e consequência foram populadas com sucesso!');
    process.exit(0);
  } catch (err) {
    console.error('❌ Erro ao popular masmorras:', err);
    process.exit(1);
  }
}

seed();
