import { randomUUID } from 'node:crypto';
import { sequelize, DefinitionTask } from '../server/models/index.js';

const defaultTasks = [
  // ─────────────────────────────────────────────────────────
  // 🏠 Categoria: DOMESTIC (21 Tarefas)
  // ─────────────────────────────────────────────────────────
  // 🟢 EASY (7)
  {
    slug: 'arrumar-cama',
    name: 'Arrumar a Própria Cama',
    description: 'Esticar o lençol, ajeitar o cobertor e posicionar os travesseiros corretamente.',
    category: 'DOMESTIC',
    difficulty: 'EASY',
    allowed_profile: 'ALL',
    reward_xp: 10,
    reward_gold: 5,
    reward_energy: 1,
    estimated_time: '5 min',
    requires_proof: true,
  },
  {
    slug: 'recolher-brinquedos',
    name: 'Recolher os Brinquedos',
    description: 'Guardar brinquedos e jogos espalhados na caixa ou estante organizada.',
    category: 'DOMESTIC',
    difficulty: 'EASY',
    allowed_profile: 'ALL',
    reward_xp: 10,
    reward_gold: 5,
    reward_energy: 1,
    estimated_time: '5-10 min',
    requires_proof: true,
  },
  {
    slug: 'roupa-suja-no-cesto',
    name: 'Roupa Suja no Cesto',
    description: 'Colocar as roupas do dia no cesto apropriado, sem deixar nenhuma peça no chão.',
    category: 'DOMESTIC',
    difficulty: 'EASY',
    allowed_profile: 'ALL',
    reward_xp: 10,
    reward_gold: 5,
    reward_energy: 1,
    estimated_time: '5 min',
    requires_proof: true,
  },
  {
    slug: 'colocar-tirar-prato',
    name: 'Colocar/Tirar o Prato da Mesa',
    description: 'Levar prato, copos e talheres usados para a pia após a refeição.',
    category: 'DOMESTIC',
    difficulty: 'EASY',
    allowed_profile: 'ALL',
    reward_xp: 15,
    reward_gold: 5,
    reward_energy: 1,
    estimated_time: '5 min',
    requires_proof: true,
  },
  {
    slug: 'alimentar-pet',
    name: 'Abastecer Água e Ração do Pet',
    description: 'Lavar e encher os potinhos de comida e água do animal de estimação.',
    category: 'DOMESTIC',
    difficulty: 'EASY',
    allowed_profile: 'ALL',
    reward_xp: 15,
    reward_gold: 10,
    reward_energy: 1,
    estimated_time: '5-10 min',
    requires_proof: true,
  },
  {
    slug: 'arrumar-mochila',
    name: 'Arrumar a Mochila da Escola',
    description: 'Conferir os cadernos do dia seguinte, estojo e garrafinha de água.',
    category: 'DOMESTIC',
    difficulty: 'EASY',
    allowed_profile: 'CHILD_ONLY',
    reward_xp: 15,
    reward_gold: 5,
    reward_energy: 1,
    estimated_time: '5-10 min',
    requires_proof: true,
  },
  {
    slug: 'regar-plantas',
    name: 'Regar as Plantas da Casa',
    description: 'Colocar a quantidade certa de água nos vasos da sala ou varanda.',
    category: 'DOMESTIC',
    difficulty: 'EASY',
    allowed_profile: 'ALL',
    reward_xp: 15,
    reward_gold: 5,
    reward_energy: 1,
    estimated_time: '5-10 min',
    requires_proof: true,
  },

  // 🟡 MEDIUM (7)
  {
    slug: 'varrer-comodo',
    name: 'Varrer um Cômodo',
    description: 'Passar a vassoura no quarto ou na sala e recolher a sujeira com a pá.',
    category: 'DOMESTIC',
    difficulty: 'MEDIUM',
    allowed_profile: 'ALL',
    reward_xp: 35,
    reward_gold: 20,
    reward_energy: 2,
    estimated_time: '15-20 min',
    requires_proof: true,
  },
  {
    slug: 'tirar-lixo',
    name: 'Tirar o Lixo da Casa',
    description: 'Amarrar os sacos de lixo (banheiro/cozinha) e colocar na lixeira principal.',
    category: 'DOMESTIC',
    difficulty: 'MEDIUM',
    allowed_profile: 'ALL',
    reward_xp: 30,
    reward_gold: 15,
    reward_energy: 2,
    estimated_time: '10-15 min',
    requires_proof: true,
  },
  {
    slug: 'lavar-louca-leve',
    name: 'Lavar a Louça Leve',
    description: 'Lavar copos, pratos e talheres (sem facas afiadas) e organizar no escorredor.',
    category: 'DOMESTIC',
    difficulty: 'MEDIUM',
    allowed_profile: 'ALL',
    reward_xp: 40,
    reward_gold: 25,
    reward_energy: 2,
    estimated_time: '20-30 min',
    requires_proof: true,
  },
  {
    slug: 'guardar-roupas',
    name: 'Guardar as Roupas Dobradas',
    description: 'Organizar as peças limpas nas gavetas e pendurar itens em cabides.',
    category: 'DOMESTIC',
    difficulty: 'MEDIUM',
    allowed_profile: 'ALL',
    reward_xp: 35,
    reward_gold: 20,
    reward_energy: 2,
    estimated_time: '15-20 min',
    requires_proof: true,
  },
  {
    slug: 'limpar-poeira',
    name: 'Limpar a Poeira dos Móveis',
    description: 'Passar pano seco ou espanador nas mesas, estantes e bancadas de toda a casa.',
    category: 'DOMESTIC',
    difficulty: 'MEDIUM',
    allowed_profile: 'ALL',
    reward_xp: 30,
    reward_gold: 15,
    reward_energy: 2,
    estimated_time: '15-20 min',
    requires_proof: true,
  },
  {
    slug: 'guardar-compras',
    name: 'Ajudar a Guardar as Compras',
    description: 'Retirar itens das sacolas e organizar mantimentos na despensa e geladeira.',
    category: 'DOMESTIC',
    difficulty: 'MEDIUM',
    allowed_profile: 'ALL',
    reward_xp: 40,
    reward_gold: 25,
    reward_energy: 2,
    estimated_time: '15-20 min',
    requires_proof: true,
  },
  {
    slug: 'passear-cachorro',
    name: 'Passear com o Cachorro',
    description: 'Dar uma volta no quarteirão com o pet, recolhendo os dejetos adequadamente.',
    category: 'DOMESTIC',
    difficulty: 'MEDIUM',
    allowed_profile: 'ALL',
    reward_xp: 45,
    reward_gold: 30,
    reward_energy: 2,
    estimated_time: '20-30 min',
    requires_proof: true,
  },

  // 🔴 HARD (7)
  {
    slug: 'limpeza-quarto',
    name: 'Limpeza Geral do Quarto',
    description: 'Varrer, passar pano no chão, organizar guarda-roupa, trocar roupa de cama e tirar o lixo.',
    category: 'DOMESTIC',
    difficulty: 'HARD',
    allowed_profile: 'ALL',
    reward_xp: 100,
    reward_gold: 70,
    reward_energy: 4,
    estimated_time: '45-60 min',
    requires_proof: true,
  },
  {
    slug: 'lavar-louca-completa',
    name: 'Lavar a Louça Completa',
    description: 'Lavar, secar e guardar todas as panelas, travessas e pratos da refeição familiar.',
    category: 'DOMESTIC',
    difficulty: 'HARD',
    allowed_profile: 'ALL',
    reward_xp: 90,
    reward_gold: 60,
    reward_energy: 4,
    estimated_time: '30-45 min',
    requires_proof: true,
  },
  {
    slug: 'passar-pano-casa',
    name: 'Passar Pano no Chão da Casa',
    description: 'Utilizar balde e rodo/mop em todas as áreas comuns (sala, cozinha e corredores).',
    category: 'DOMESTIC',
    difficulty: 'HARD',
    allowed_profile: 'ALL',
    reward_xp: 100,
    reward_gold: 70,
    reward_energy: 4,
    estimated_time: '40-60 min',
    requires_proof: true,
  },
  {
    slug: 'limpar-banheiro',
    name: 'Higienização do Banheiro',
    description: 'Limpar pia, espelho, recolher o lixo e higienizar o vaso sanitário.',
    category: 'DOMESTIC',
    difficulty: 'HARD',
    allowed_profile: 'ALL',
    reward_xp: 120,
    reward_gold: 80,
    reward_energy: 4,
    estimated_time: '30-45 min',
    requires_proof: true,
  },
  {
    slug: 'preparar-refeicao',
    name: 'Preparar uma Refeição Familiar',
    description: 'Cozinhar um prato completo para a família (ex: omelete, massa, salada, lanche).',
    category: 'DOMESTIC',
    difficulty: 'HARD',
    allowed_profile: 'ADULT_ONLY',
    reward_xp: 110,
    reward_gold: 75,
    reward_energy: 4,
    estimated_time: '40-60 min',
    requires_proof: true,
  },
  {
    slug: 'lavar-quintal',
    name: 'Lavar o Quintal ou Garagem',
    description: 'Varrer folhas secas, jogar água e esfregar o piso com vassoura pesada.',
    category: 'DOMESTIC',
    difficulty: 'HARD',
    allowed_profile: 'ALL',
    reward_xp: 120,
    reward_gold: 85,
    reward_energy: 4,
    estimated_time: '45-60 min',
    requires_proof: true,
  },
  {
    slug: 'varal-completo',
    name: 'Estender e Recolher Varal Completo',
    description: 'Tirar roupas da máquina, estender no varal e dobrar todas quando secarem.',
    category: 'DOMESTIC',
    difficulty: 'HARD',
    allowed_profile: 'ALL',
    reward_xp: 80,
    reward_gold: 50,
    reward_energy: 4,
    estimated_time: '30-45 min',
    requires_proof: true,
  },

  // ─────────────────────────────────────────────────────────
  // 📚 Categoria: STUDY (7 Tarefas)
  // ─────────────────────────────────────────────────────────
  // 🟢 EASY (2)
  {
    slug: 'ler-20min',
    name: 'Ler por 20 Minutos',
    description: 'Ler qualquer livro, revista ou artigo educativo por pelo menos 20 minutos seguidos.',
    category: 'STUDY',
    difficulty: 'EASY',
    allowed_profile: 'ALL',
    reward_xp: 30,
    reward_gold: 15,
    reward_energy: 1,
    estimated_time: '20 min',
    requires_proof: true,
  },
  {
    slug: 'revisar-caderno',
    name: 'Revisar o Caderno do Dia',
    description: 'Ler e organizar as anotações feitas em sala de aula no dia.',
    category: 'STUDY',
    difficulty: 'EASY',
    allowed_profile: 'CHILD_ONLY',
    reward_xp: 20,
    reward_gold: 10,
    reward_energy: 1,
    estimated_time: '15-20 min',
    requires_proof: true,
  },

  // 🟡 MEDIUM (3)
  {
    slug: 'estudar-materia',
    name: 'Estudar uma Matéria',
    description: 'Focar em uma disciplina escolar por pelo menos 30 minutos usando o Foco do Herói.',
    category: 'STUDY',
    difficulty: 'MEDIUM',
    allowed_profile: 'CHILD_ONLY',
    reward_xp: 70,
    reward_gold: 40,
    reward_energy: 2,
    estimated_time: '30 min',
    requires_proof: true,
  },
  {
    slug: 'fazer-licao',
    name: 'Fazer a Lição de Casa',
    description: 'Concluir todas as tarefas escolares do dia antes do jantar.',
    category: 'STUDY',
    difficulty: 'MEDIUM',
    allowed_profile: 'CHILD_ONLY',
    reward_xp: 60,
    reward_gold: 35,
    reward_energy: 2,
    estimated_time: '30-45 min',
    requires_proof: true,
  },
  {
    slug: 'aprender-algo-novo',
    name: 'Aprender Algo Novo',
    description: 'Assistir a um vídeo educativo, tutorial ou curso por pelo menos 30 minutos.',
    category: 'STUDY',
    difficulty: 'MEDIUM',
    allowed_profile: 'ALL',
    reward_xp: 50,
    reward_gold: 30,
    reward_energy: 2,
    estimated_time: '30 min',
    requires_proof: true,
  },

  // 🔴 HARD (2)
  {
    slug: 'estudar-prova',
    name: 'Estudar para uma Prova',
    description: 'Sessão de estudo de pelo menos 45 minutos focada em uma prova ou avaliação.',
    category: 'STUDY',
    difficulty: 'HARD',
    allowed_profile: 'CHILD_ONLY',
    reward_xp: 120,
    reward_gold: 80,
    reward_energy: 4,
    estimated_time: '45-60 min',
    requires_proof: true,
  },
  {
    slug: 'projeto-escolar',
    name: 'Concluir um Projeto Escolar',
    description: 'Finalizar uma etapa importante de um trabalho escolar ou apresentação.',
    category: 'STUDY',
    difficulty: 'HARD',
    allowed_profile: 'CHILD_ONLY',
    reward_xp: 130,
    reward_gold: 90,
    reward_energy: 4,
    estimated_time: '60+ min',
    requires_proof: true,
  },

  // ─────────────────────────────────────────────────────────
  // 💪 Categoria: HEALTH (6 Tarefas)
  // ─────────────────────────────────────────────────────────
  // 🟢 EASY (3)
  {
    slug: 'escovar-dentes',
    name: 'Escovar os Dentes (3x ao dia)',
    description: 'Escovar os dentes após o café, almoço e jantar.',
    category: 'HEALTH',
    difficulty: 'EASY',
    allowed_profile: 'ALL',
    reward_xp: 10,
    reward_gold: 5,
    reward_energy: 1,
    estimated_time: '5 min',
    requires_proof: true,
  },
  {
    slug: 'beber-agua',
    name: 'Beber Água ao Longo do Dia',
    description: 'Consumir pelo menos 1,5 litro de água durante o dia.',
    category: 'HEALTH',
    difficulty: 'EASY',
    allowed_profile: 'ALL',
    reward_xp: 15,
    reward_gold: 8,
    reward_energy: 1,
    estimated_time: 'Dia inteiro',
    requires_proof: true,
  },
  {
    slug: 'dormir-no-horario',
    name: 'Dormir no Horário Combinado',
    description: 'Estar na cama com as luzes apagadas no horário combinado pela família.',
    category: 'HEALTH',
    difficulty: 'EASY',
    allowed_profile: 'CHILD_ONLY',
    reward_xp: 20,
    reward_gold: 10,
    reward_energy: 1,
    estimated_time: '—',
    requires_proof: true,
  },

  // 🟡 MEDIUM (3)
  {
    slug: 'praticar-esporte',
    name: 'Praticar um Esporte ou Atividade Física',
    description: '30 minutos de qualquer atividade física: jogar bola, andar de bike, dançar, academia.',
    category: 'HEALTH',
    difficulty: 'MEDIUM',
    allowed_profile: 'ALL',
    reward_xp: 60,
    reward_gold: 35,
    reward_energy: 2,
    estimated_time: '30 min',
    requires_proof: true,
  },
  {
    slug: 'caminhar',
    name: 'Dar uma Caminhada',
    description: 'Caminhar pelo bairro por pelo menos 20 minutos.',
    category: 'HEALTH',
    difficulty: 'MEDIUM',
    allowed_profile: 'ALL',
    reward_xp: 40,
    reward_gold: 25,
    reward_energy: 2,
    estimated_time: '20-30 min',
    requires_proof: true,
  },
  {
    slug: 'comer-verdura',
    name: 'Comer Verdura ou Fruta na Refeição',
    description: 'Incluir legume, verdura ou fruta em pelo menos uma refeição do dia.',
    category: 'HEALTH',
    difficulty: 'MEDIUM',
    allowed_profile: 'ALL',
    reward_xp: 30,
    reward_gold: 20,
    reward_energy: 2,
    estimated_time: '—',
    requires_proof: true,
  },

  // ─────────────────────────────────────────────────────────
  // 🎨 Categoria: CREATIVE (4 Tarefas)
  // ─────────────────────────────────────────────────────────
  // 🟡 MEDIUM (2)
  {
    slug: 'desenhar',
    name: 'Desenhar ou Colorir',
    description: 'Criar um desenho ou colorir uma ilustração por pelo menos 20 minutos.',
    category: 'CREATIVE',
    difficulty: 'MEDIUM',
    allowed_profile: 'ALL',
    reward_xp: 40,
    reward_gold: 25,
    reward_energy: 2,
    estimated_time: '20-30 min',
    requires_proof: true,
  },
  {
    slug: 'montar-projeto-manual',
    name: 'Fazer um Projeto Manual',
    description: 'Montar, construir ou criar algo com materiais artísticos (Lego, argila, recorte, colagem).',
    category: 'CREATIVE',
    difficulty: 'MEDIUM',
    allowed_profile: 'ALL',
    reward_xp: 50,
    reward_gold: 30,
    reward_energy: 2,
    estimated_time: '30 min',
    requires_proof: true,
  },

  // 🔴 HARD (2)
  {
    slug: 'artesanato-peca',
    name: 'Concluir uma Peça de Artesanato',
    description: 'Finalizar uma peça artesanal completa (crochê, pintura, bijuteria, etc.).',
    category: 'CREATIVE',
    difficulty: 'HARD',
    allowed_profile: 'ADULT_ONLY',
    reward_xp: 130,
    reward_gold: 90,
    reward_energy: 4,
    estimated_time: '60+ min',
    requires_proof: true,
  },
  {
    slug: 'projeto-criativo-completo',
    name: 'Concluir um Projeto Criativo',
    description: 'Finalizar um projeto de arte, design, música ou escrita do início ao fim.',
    category: 'CREATIVE',
    difficulty: 'HARD',
    allowed_profile: 'ALL',
    reward_xp: 120,
    reward_gold: 80,
    reward_energy: 4,
    estimated_time: '60+ min',
    requires_proof: true,
  },

  // ─────────────────────────────────────────────────────────
  // 🤝 Categoria: SOCIAL (4 Tarefas)
  // ─────────────────────────────────────────────────────────
  // 🟢 EASY (2)
  {
    slug: 'ajudar-familiar',
    name: 'Ajudar um Familiar Sem Ser Pedido',
    description: 'Identificar uma necessidade de alguém da família e ajudar espontaneamente.',
    category: 'SOCIAL',
    difficulty: 'EASY',
    allowed_profile: 'ALL',
    reward_xp: 25,
    reward_gold: 15,
    reward_energy: 1,
    estimated_time: 'Variável',
    requires_proof: true,
  },
  {
    slug: 'pedir-desculpa',
    name: 'Pedir Desculpa Quando Errar',
    description: 'Reconhecer um erro e pedir desculpa sincera à pessoa afetada.',
    category: 'SOCIAL',
    difficulty: 'EASY',
    allowed_profile: 'ALL',
    reward_xp: 20,
    reward_gold: 10,
    reward_energy: 1,
    estimated_time: '—',
    requires_proof: true,
  },

  // 🟡 MEDIUM (2)
  {
    slug: 'momento-familia',
    name: 'Participar de um Momento em Família',
    description: 'Jogar um jogo de tabuleiro, assistir a um filme ou fazer uma atividade juntos.',
    category: 'SOCIAL',
    difficulty: 'MEDIUM',
    allowed_profile: 'ALL',
    reward_xp: 50,
    reward_gold: 30,
    reward_energy: 2,
    estimated_time: '30-60 min',
    requires_proof: true,
  },
  {
    slug: 'ligar-parente',
    name: 'Ligar ou Mandar Mensagem para um Parente',
    description: 'Entrar em contato com avós, tios ou primos de forma carinhosa.',
    category: 'SOCIAL',
    difficulty: 'MEDIUM',
    allowed_profile: 'ALL',
    reward_xp: 35,
    reward_gold: 20,
    reward_energy: 2,
    estimated_time: '15 min',
    requires_proof: true,
  },
];

async function seedDefinitionTasks() {
  try {
    console.log('🔄 Sincronizando tabela definition_tasks e inserindo o catálogo de 42 tarefas...');
    await sequelize.authenticate();
    await DefinitionTask.sync({ alter: true });

    let inserted = 0;
    let updated = 0;

    for (const taskData of defaultTasks) {
      let existing = await DefinitionTask.findOne({ where: { slug: taskData.slug } });
      if (!existing) {
        await DefinitionTask.create({
          id: randomUUID().toLowerCase(),
          ...taskData,
        });
        inserted++;
      } else {
        await existing.update(taskData);
        updated++;
      }
    }

    console.log(`🎉 Catálogo de Tarefas sincronizado com sucesso! Novos: ${inserted}, Atualizados: ${updated}, Total: ${defaultTasks.length}`);
    process.exit(0);
  } catch (error) {
    console.error('❌ Erro ao popular o catálogo de tarefas definition_tasks:', error);
    process.exit(1);
  }
}

seedDefinitionTasks();
