import { randomUUID } from 'crypto';
import {
  FamilyDungeonAdventure,
  FamilyDungeonScene,
  FamilyDungeonAction,
} from '../server/models/index.js';

const ADVENTURES = [
  {
    code: 'covil_goblin_poeira',
    title: 'O Covil do Goblin da Poeira',
    description: 'Um redemoinho de sujeira e bagunça tomou conta do sótão ancestral da mansão. O Goblin da Poeira escondeu pertences valiosos entre pilhas de desordem. Somente um herói com bravura e espírito de organização pode derrotá-lo!',
    cover_icon: '🧹',
    difficulty_level: 'EASY',
    energy_cost: 5,
    base_gold_reward: 45,
    base_xp_reward: 70,
    scenes: [
      {
        step_order: 1,
        scene_code: 'sotao_entrada',
        title: 'Os Degraus do Sótão Esquecido',
        narrative_text: 'Ao empurrar o alçapão range-dentes do sótão, uma nuvem cinzenta sobe no ar. O corredor inicial está totalmente bloqueado por velhas caixas pesadas e móveis desordenados que impedem a passagem. Barulhos de passos zombeteiros ecoam ao fundo.',
        scene_icon: '🏚️',
        is_final_scene: false,
        actions: [
          {
            action_number: 1,
            title: 'Erguer e remover a pilha de caixas pesadas',
            attribute_code: 'str',
            difficulty_dc: 10,
            success_text: 'Com um esforço muscular exemplar, você levanta o baú de ferro e desobstrui o corredor sem fazer barulho!',
            failure_text: 'A caixa escorrega de suas mãos e desaba sobre o seu pé, causando um baque doloroso (-10 HP)!',
            failure_damage: 10,
            bonus_gold: 5,
          },
          {
            action_number: 2,
            title: 'Esgueirar-se ágil pelas frestas estreitas dos móveis',
            attribute_code: 'agi',
            difficulty_dc: 10,
            success_text: 'Com a flexibilidade de um gato, você desliza entre as frestas poeirentas sem derrubar nenhum objeto!',
            failure_text: 'Sua capa enrosca em um prego enferrujado. Ao puxar com pressa, você bate o ombro no batente (-10 HP)!',
            failure_damage: 10,
            bonus_gold: 5,
          },
          {
            action_number: 3,
            title: 'Analisar o centro de gravidade e retirar a caixa-chave',
            attribute_code: 'int',
            difficulty_dc: 9,
            success_text: 'Sua mente lógica identifica exatamente qual caixa sustenta o monte. Ao puxá-la, a pilha se acomoda suavemente!',
            failure_text: 'O cálculo falha e uma chuva de livros antigos despenca na sua cabeça (-10 HP)!',
            failure_damage: 10,
            bonus_gold: 8,
          },
        ],
      },
      {
        step_order: 2,
        scene_code: 'nevoa_poeira',
        title: 'A Névoa de Poeira Encantada',
        narrative_text: 'Você adentra um salão circular onde um redemoinho cinzento gira furiosamente. A poeira mágica queima a garganta e cega a visão, tentando fazê-lo tossir e recuar. Pequenas risadinhas estridentes zombam da sua insistência.',
        scene_icon: '🌪️',
        is_final_scene: false,
        actions: [
          {
            action_number: 1,
            title: 'Prender a respiração e marchar firme contra o vórtice',
            attribute_code: 'con',
            difficulty_dc: 10,
            success_text: 'Seus pulmões de ferro e determinação inabalável atravessam o vendaval cinzento sem vacilar!',
            failure_text: 'O pó asfixiante entra no seu peito, provocando uma crise de tosse violenta (-10 HP)!',
            failure_damage: 10,
            bonus_gold: 5,
          },
          {
            action_number: 2,
            title: 'Entoar o hino de honra da família para soprar o medo',
            attribute_code: 'cha',
            difficulty_dc: 10,
            success_text: 'Sua voz melodiosa ressoa com luz acolhedora; a poeira encantada se dissipa ante a pureza do hino!',
            failure_text: 'Sua voz treme com o frio da sala, atraindo uma rajada de vento acre na sua face (-10 HP)!',
            failure_damage: 10,
            bonus_gold: 6,
          },
          {
            action_number: 3,
            title: 'Procurar às cegas uma fresta com corrente de ar puro',
            attribute_code: 'luk',
            difficulty_dc: 11,
            success_text: 'O destino sorri! Sua mão encontra um alçapão de ventilação que sopra ar fresco e limpa o salão!',
            failure_text: 'Você tateia no escuro e esbarra numa viga de sustentação com o joelho (-10 HP)!',
            failure_damage: 10,
            bonus_gold: 7,
          },
        ],
      },
      {
        step_order: 3,
        scene_code: 'piso_brinquedos',
        title: 'O Campo de Armadilhas Pontiagudas',
        narrative_text: 'O caminho para a câmara principal foi semeado com blocos triangulares afiados, patins de rodas soltas e peças de encaixe espalhadas no chão. Dar um passo em falso aqui é garantia de dor aguda na sola do pé!',
        scene_icon: '🧩',
        is_final_scene: false,
        actions: [
          {
            action_number: 1,
            title: 'Saltar de viga em viga pelo teto com destreza física',
            attribute_code: 'agi',
            difficulty_dc: 11,
            success_text: 'Você salta acrobaticamente entre os caibros do teto, pousando com leveza do outro lado!',
            failure_text: 'O salto fica curto! Você cai de pé sobre um bloco pontiagudo de quina viva (-12 HP)!',
            failure_damage: 12,
            bonus_gold: 6,
          },
          {
            action_number: 2,
            title: 'Desenhar uma rota lógica memorizando as lacunas do piso',
            attribute_code: 'int',
            difficulty_dc: 10,
            success_text: 'Com precisão analítica, você traça a rota perfeita e caminha com passos milimétricos sem risco!',
            failure_text: 'Uma distração momentânea faz seu pé escorregar sobre uma rodinha de carrinho (-12 HP)!',
            failure_damage: 12,
            bonus_gold: 7,
          },
          {
            action_number: 3,
            title: 'Puxar um tapete grosso para forrar o chão e proteger a sola',
            attribute_code: 'str',
            difficulty_dc: 11,
            success_text: 'Usando sua força, você arrasta uma pesada passadeira de veludo que cobre todas as armadilhas!',
            failure_text: 'O tapete rasga no meio do caminho e você torce o tornozelo no estirão (-12 HP)!',
            failure_damage: 12,
            bonus_gold: 5,
          },
        ],
      },
      {
        step_order: 4,
        scene_code: 'duelo_goblin',
        title: 'O Confronto com o Goblin da Poeira',
        narrative_text: 'Em cima de uma pilha de malas velhas surge a criatura: o Goblin da Poeira! Olhos amarelos faiscantes, rindo com escárnio e brandindo um espanador sombrio que dispara bolas de poeira negra. "Ninguém limpa o meu reino!", grita ele.',
        scene_icon: '👾',
        is_final_scene: false,
        actions: [
          {
            action_number: 1,
            title: 'Investir bravamente com sua arma e cortar o espanador',
            attribute_code: 'str',
            difficulty_dc: 12,
            success_text: 'Seu golpe certeiro decepa a haste do espanador mágico! O goblin cai de costas, apavorado!',
            failure_text: 'O monstro desvia rápido e atinge seu peitoral com uma rajada de fumaça cinzenta (-14 HP)!',
            failure_damage: 14,
            bonus_gold: 10,
          },
          {
            action_number: 2,
            title: 'Efetuar rolamento rápido e flanquear a criatura pelas costas',
            attribute_code: 'agi',
            difficulty_dc: 11,
            success_text: 'Em um piscar de olhos você reaparece atrás do monstro e o encurrala com seu escudo de luz!',
            failure_text: 'O goblin antecipa seu movimento e joga um tapete de poeira nos seus olhos (-14 HP)!',
            failure_damage: 14,
            bonus_gold: 8,
          },
          {
            action_number: 3,
            title: 'Proclamar a Ordem da Casa: "Aqui a Preguiça Não Tem Vez!"',
            attribute_code: 'cha',
            difficulty_dc: 11,
            success_text: 'Sua autoridade e firmeza moral quebram a maldição da bagunça! O monstro encolhe e se dissolve!',
            failure_text: 'As palavras saem sem convicção suficiente e o goblin gargalha, lançando uma onda de choque (-14 HP)!',
            failure_damage: 14,
            bonus_gold: 10,
          },
        ],
      },
      {
        step_order: 5,
        scene_code: 'bau_tesouro_goblin',
        title: 'A Câmara do Baú de Pinho Dourado',
        narrative_text: 'Com a desordem vencida, raios de sol atravessam a janela do sótão, iluminando um magnífico Baú de Pinho talhado com runas de ouro. O baú contém as relíquias do lar resgatadas da escuridão!',
        scene_icon: '👑',
        is_final_scene: true,
        actions: [
          {
            action_number: 1,
            title: 'Decifrar as três runas do cadeado ancestral',
            attribute_code: 'int',
            difficulty_dc: 10,
            success_text: 'As runas brilham em azul safira! O ferrolho desliza suavemente com um tilintar harmonioso!',
            failure_text: 'Um choque mágico menor atinge suas pontas dos dedos, mas a fechadura cede (-8 HP)!',
            failure_damage: 8,
            bonus_gold: 15,
          },
          {
            action_number: 2,
            title: 'Utilizar a Gazua da Sorte girando os pinos de metal',
            attribute_code: 'luk',
            difficulty_dc: 9,
            success_text: 'Click! Um estalo triunfal ecoa no sótão e a tampa se abre de par em par com brilho dourado!',
            failure_text: 'A gazua entorta, forçando você a puxar a trava na marra com um arranhão no braço (-8 HP)!',
            failure_damage: 8,
            bonus_gold: 15,
          },
          {
            action_number: 3,
            title: 'Erguer a tampa de carvalho maciço com vigor heróico',
            attribute_code: 'con',
            difficulty_dc: 10,
            success_text: 'Seus músculos firmes sustentam o peso da tampa de chumbo e revelam o fabuloso tesouro!',
            failure_text: 'A tampa é incrivelmente pesada e machuca sua mão antes de abrir completamente (-8 HP)!',
            failure_damage: 8,
            bonus_gold: 12,
          },
        ],
      },
    ],
  },
  {
    code: 'torre_devorador_paginas',
    title: 'A Torre do Devorador de Páginas',
    description: 'No alto da biblioteca flutuante do reino, o Devorador de Páginas está roendo os segredos dos livros de conhecimento e lições escolares. Decifre os enigmas arcanos, prove sua inteligência e salve a sabedoria da família!',
    cover_icon: '📚',
    difficulty_level: 'MEDIUM',
    energy_cost: 5,
    base_gold_reward: 60,
    base_xp_reward: 90,
    scenes: [
      {
        step_order: 1,
        scene_code: 'portao_biblioteca',
        title: 'O Portal dos Enigmas Gravados',
        narrative_text: 'Você chega diante do enorme portal de bronze da Torre do Saber. Na porta, letras brilhantes formam uma charada: "Quanto mais você tem de mim, menos você vê no escuro. Quem sou eu?". Três fechaduras mágicas aguardam sua resposta.',
        scene_icon: '🚪',
        is_final_scene: false,
        actions: [
          {
            action_number: 1,
            title: 'Responder com convicção: "A Luz!" (Canalizar faísca arcana)',
            attribute_code: 'int',
            difficulty_dc: 11,
            success_text: 'As letras brilham em dourado radiante! A resposta está correta e os pesados ferrolhos se abrem!',
            failure_text: 'Sua voz titubeia na resposta; uma fagulha de rejeição mágica queima sua túnica (-12 HP)!',
            failure_damage: 12,
            bonus_gold: 8,
          },
          {
            action_number: 2,
            title: 'Examinar o mecanismo de contrapeso das engrenagens',
            attribute_code: 'agi',
            difficulty_dc: 12,
            success_text: 'Seus dedos rápidos encontram a trava de emergência e destrancam a porta mecanicamente!',
            failure_text: 'Uma das engrenagens range e prende sua luva nas correntes de tração (-12 HP)!',
            failure_damage: 12,
            bonus_gold: 7,
          },
          {
            action_number: 3,
            title: 'Forçar as duas batentes de bronze com ombro firme',
            attribute_code: 'str',
            difficulty_dc: 13,
            success_text: 'Com um urro de determinação, você supera a trava arcaica na força bruta!',
            failure_text: 'O bronze encantado repele seu impacto com uma onda de choque reverberante (-12 HP)!',
            failure_damage: 12,
            bonus_gold: 6,
          },
        ],
      },
      {
        step_order: 2,
        scene_code: 'escadaria_livros',
        title: 'A Escadaria dos Tomos Flutuantes',
        narrative_text: 'O interior da torre é um abismo espiral sem chão fixo. Para subir, você precisa saltar sobre grossos livros de feitiços que flutuam no ar ao sabor de ventos mágicos inconstantes.',
        scene_icon: '📖',
        is_final_scene: false,
        actions: [
          {
            action_number: 1,
            title: 'Saltar com agilidade e ritmo impecável de capa em capa',
            attribute_code: 'agi',
            difficulty_dc: 12,
            success_text: 'Leve como uma pluma, você corre sobre os livros voadores sem fazê-los oscilar nem um centímetro!',
            failure_text: 'Um tomo fecha de repente! Você perde o equilíbrio e raspa as pernas na beirada de pedra (-14 HP)!',
            failure_damage: 14,
            bonus_gold: 8,
          },
          {
            action_number: 2,
            title: 'Ler os títulos em latim para pisar apenas nos livros estáveis',
            attribute_code: 'int',
            difficulty_dc: 11,
            success_text: 'Você nota que os tratados de Astronomia possuem aterrissagem estável e sobe tranquilamente!',
            failure_text: 'Você confunde um tomo de Levitação com um de Queda Livre e despenca alguns metros (-14 HP)!',
            failure_damage: 14,
            bonus_gold: 9,
          },
          {
            action_number: 3,
            title: 'Confiar na sorte e saltar com fé no fluxo dos ventos',
            attribute_code: 'luk',
            difficulty_dc: 12,
            success_text: 'Uma brisa repentina ergue um enorme atlas bem sob os seus pés, levando você ao topo!',
            failure_text: 'O vento cessa no momento crucial e você colide contra a coluna central da torre (-14 HP)!',
            failure_damage: 14,
            bonus_gold: 10,
          },
        ],
      },
      {
        step_order: 3,
        scene_code: 'sala_pergaminhos',
        title: 'O Labirinto das Letras Vivas',
        narrative_text: 'Você chega a um salão forrado de estantes infinitas. As letras fugiram das páginas e formam enxames de tinta que rodopiam como vespas. Quem for atingido esquece o que acabou de estudar!',
        scene_icon: '📜',
        is_final_scene: false,
        actions: [
          {
            action_number: 1,
            title: 'Conjurar um escudo de foco e concentração inabalável',
            attribute_code: 'con',
            difficulty_dc: 12,
            success_text: 'Sua mente disciplinada repele o enxame de dispersão! As letras recuam ordenadas!',
            failure_text: 'O turbilhão de letras penetra sua defesa mental, causando tontura e dor de cabeça (-12 HP)!',
            failure_damage: 12,
            bonus_gold: 8,
          },
          {
            action_number: 2,
            title: 'Citar uma poesia harmoniosa para pacificar as palavras',
            attribute_code: 'cha',
            difficulty_dc: 11,
            success_text: 'Ao declamar versos de bravura, as letras se encantam com sua voz e voltam dóceis aos livros!',
            failure_text: 'Você esquece a rima no meio da frase e as palavras rebeldes ferroam seus braços (-12 HP)!',
            failure_damage: 12,
            bonus_gold: 9,
          },
          {
            action_number: 3,
            title: 'Mover-se em zigue-zague veloz esquivando dos pingos de tinta',
            attribute_code: 'agi',
            difficulty_dc: 13,
            success_text: 'Com reflexos de campeão, você dribla cada gota e alcança o outro lado intacto!',
            failure_text: 'Uma saraivada de tinta mágica queima sua bochecha antes de você conseguir se abrigar (-12 HP)!',
            failure_damage: 12,
            bonus_gold: 7,
          },
        ],
      },
      {
        step_order: 4,
        scene_code: 'confronto_devorador',
        title: 'O Duelo contra o Devorador de Páginas',
        narrative_text: 'No topo da cúpula, uma fera monstruosa feita de capas de couro, pergaminhos rasgados e dentes de penas afiadas mastiga enciclopédias: é o Devorador de Páginas! Seus olhos brilham com a preguiça intelectual dos maus estudantes.',
        scene_icon: '🐉',
        is_final_scene: false,
        actions: [
          {
            action_number: 1,
            title: 'Lançar um enigma lógico irrespondível para paralisá-lo',
            attribute_code: 'int',
            difficulty_dc: 12,
            success_text: '"O que tem raiz mas não é árvore, sobe sem andar e cai sem chorar?". O monstro entra em curto-circuito e cai!',
            failure_text: 'O monstro engole seu enigma e sopra uma rajada de páginas em chamas na sua direção (-16 HP)!',
            failure_damage: 16,
            bonus_gold: 12,
          },
          {
            action_number: 2,
            title: 'Investir com a espada encantada direto no coração de papiro',
            attribute_code: 'str',
            difficulty_dc: 13,
            success_text: 'Seu corte heroico perfura o núcleo arcano da criatura, libertando todas as letras aprisionadas!',
            failure_text: 'A mandíbula de madeira do monstro golpeia seu escudo com violência estarrecedora (-16 HP)!',
            failure_damage: 16,
            bonus_gold: 10,
          },
          {
            action_number: 3,
            title: 'Aproveitar a brecha de ataque e cegá-lo com pó rúnico',
            attribute_code: 'luk',
            difficulty_dc: 12,
            success_text: 'Um golpe de pura sorte acerta os olhos da fera, fazendo-a tropeçar da balaustrada!',
            failure_text: 'O pó sopra de volta nos seus olhos e você recebe uma chicotada de pergaminho (-16 HP)!',
            failure_damage: 16,
            bonus_gold: 11,
          },
        ],
      },
      {
        step_order: 5,
        scene_code: 'bau_tomo_ancestral',
        title: 'O Santuário do Baú Arcano',
        narrative_text: 'Com o Devorador derrotado, os tomos da sabedoria voltam às estantes reluzindo em harmonia. No centro do tablado surge o Baú de Safira da Sabedoria, trancado com um segredo matemático reluzente.',
        scene_icon: '💎',
        is_final_scene: true,
        actions: [
          {
            action_number: 1,
            title: 'Resolver a equação rúnica de abertura dos arcanos',
            attribute_code: 'int',
            difficulty_dc: 11,
            success_text: 'Brilhante! A equação se completa e as trancas deslizam com uma chuva de estrelas azuis!',
            failure_text: 'O circuito mágico dá um estalo na sua mão antes de abrir a tampa de cristal (-10 HP)!',
            failure_damage: 10,
            bonus_gold: 20,
          },
          {
            action_number: 2,
            title: 'Utilizar sua empatia e espírito de liderança familiar',
            attribute_code: 'cha',
            difficulty_dc: 12,
            success_text: 'O baú reconhece o coração nobre de um herói que valoriza o saber e se abre com deferência!',
            failure_text: 'A energia é intensa demais e descarrega um pulso eletrostático no seu peito (-10 HP)!',
            failure_damage: 10,
            bonus_gold: 18,
          },
          {
            action_number: 3,
            title: 'Sustentar os selos de proteção com vigor corporal',
            attribute_code: 'con',
            difficulty_dc: 12,
            success_text: 'Sua resistência heróica dissipa os últimos resquícios da maldição e liberta os tesouros!',
            failure_text: 'O esforço consome suas energias, mas a vitória é consumada com bravura (-10 HP)!',
            failure_damage: 10,
            bonus_gold: 15,
          },
        ],
      },
    ],
  },
  {
    code: 'catacumbas_procrastinacao',
    title: 'As Catacumbas da Procrastinação Eterna',
    description: 'Um labirinto subterrâneo onde o tempo passa devagar e uma gosma mágica chamada "Depois Eu Faço" tenta prender os heróis no sono eterno. O Titã da Procrastinação guarda o tesouro dos minutos perdidos!',
    cover_icon: '⏳',
    difficulty_level: 'HARD',
    energy_cost: 5,
    base_gold_reward: 75,
    base_xp_reward: 110,
    scenes: [
      {
        step_order: 1,
        scene_code: 'catacumbas_entrada',
        title: 'O Pântano do "Depois Eu Faço"',
        narrative_text: 'Ao descer os degraus de pedra úmida, seus pés afundam em um lodo roxo pegajoso. Vozes sussurram no ar: "Descanse um pouco... Para que fazer agora? Deixe para amanhã...". Seus membros começam a ficar pesados como chumbo.',
        scene_icon: '🕳️',
        is_final_scene: false,
        actions: [
          {
            action_number: 1,
            title: 'Rejeitar a preguiça com um grito de disciplina e marcha férrea',
            attribute_code: 'con',
            difficulty_dc: 13,
            success_text: 'Sua vontade de aço corta a letargia! Suas pernas rasgam o lodo com vigor inabalável!',
            failure_text: 'A gosma roxa suga sua energia vital, drenando seu vigor com um torpor gélido (-15 HP)!',
            failure_damage: 15,
            bonus_gold: 10,
          },
          {
            action_number: 2,
            title: 'Saltar sobre pedras secas antes que o lodo se expanda',
            attribute_code: 'agi',
            difficulty_dc: 14,
            success_text: 'Com velocidade supersônica, você quica sobre as pedras pontiagudas sem tocar no pântano!',
            failure_text: 'Uma pedra cede sob sua bota e você afunda até o joelho no pântano sonolento (-15 HP)!',
            failure_damage: 15,
            bonus_gold: 9,
          },
          {
            action_number: 3,
            title: 'Focar na satisfação do dever cumprido e avançar focado',
            attribute_code: 'int',
            difficulty_dc: 13,
            success_text: 'Sua clareza mental neutraliza o feitiço psicológico da procrastinação com sabedoria!',
            failure_text: 'Pensamentos de adiamento nublam sua mente e você cambaleia no chão úmido (-15 HP)!',
            failure_damage: 15,
            bonus_gold: 11,
          },
        ],
      },
      {
        step_order: 2,
        scene_code: 'pendulos_ampulheta',
        title: 'O Corredor dos Pêndulos de Areia',
        narrative_text: 'O teto desta galeria estreita é guarnecido por gigantescas lâminas em forma de ampulhetas que oscilam em ritmo descompassado. Um aviso diz: "Quem perde tempo, perde a vida".',
        scene_icon: '⏱️',
        is_final_scene: false,
        actions: [
          {
            action_number: 1,
            title: 'Calcular a cadência dos pêndulos e atravessar no tempo exato',
            attribute_code: 'int',
            difficulty_dc: 13,
            success_text: 'Cronometragem perfeita! Você passa como uma sombra entre as lâminas no milissegundo certo!',
            failure_text: 'O cálculo falha por um instante e a haste de bronze acerta suas costelas (-16 HP)!',
            failure_damage: 16,
            bonus_gold: 12,
          },
          {
            action_number: 2,
            title: 'Deslizar pelo piso molhado em alta velocidade',
            attribute_code: 'agi',
            difficulty_dc: 14,
            success_text: 'Você mergulha rente ao chão, deslizando por baixo das lâminas mortais com audácia pura!',
            failure_text: 'O atrito freia seu deslize e a borda de uma ampulheta raspa seu ombro (-16 HP)!',
            failure_damage: 16,
            bonus_gold: 10,
          },
          {
            action_number: 3,
            title: 'Sustentar o escudo reforçado contra um golpe direto',
            attribute_code: 'str',
            difficulty_dc: 14,
            success_text: 'Com força hercúlea, você apara o pêndulo com o broquel e o joga para trás, abrindo caminho!',
            failure_text: 'A força do pêndulo esmaga seu escudo contra o peito, jogando você no chão (-16 HP)!',
            failure_damage: 16,
            bonus_gold: 11,
          },
        ],
      },
      {
        step_order: 3,
        scene_code: 'espelho_desculpas',
        title: 'O Espelho das Mil Desculpas',
        narrative_text: 'Uma barreira translúcida de vidro encantado reflete sua imagem, mas seu reflexo mente dizendo: "Você já trabalhou demais hoje... Você merece rolar feeds e jogar videogame por 6 horas sem parar...".',
        scene_icon: '🪞',
        is_final_scene: false,
        actions: [
          {
            action_number: 1,
            title: 'Quebrar a ilusão com a voz da verdade e honra familiar',
            attribute_code: 'cha',
            difficulty_dc: 13,
            success_text: '"Primeiro o dever, depois o lazer!". O espelho de mentiras racha e explode em pó de vidro inofensivo!',
            failure_text: 'A dúvida penetra seu coração e uma rajada de vidro encantado corta seus braços (-15 HP)!',
            failure_damage: 15,
            bonus_gold: 12,
          },
          {
            action_number: 2,
            title: 'Arremessar sua arma com toda a força contra o vidro',
            attribute_code: 'str',
            difficulty_dc: 14,
            success_text: 'A arma voa com fúria destrutiva e despedaça a ilusão em mil pedaços!',
            failure_text: 'A arma ricocheteia no vidro mágico e atinge seu joelho na volta (-15 HP)!',
            failure_damage: 15,
            bonus_gold: 10,
          },
          {
            action_number: 3,
            title: 'Confiar na sorte e encontrar a rachadura oculta do vidro',
            attribute_code: 'luk',
            difficulty_dc: 13,
            success_text: 'Seus olhos batem exatamente no ponto fraco da estrutura, desmontando o espelho com um toque leve!',
            failure_text: 'Você toca no lugar errado e um choque de desânimo invade sua espinha (-15 HP)!',
            failure_damage: 15,
            bonus_gold: 11,
          },
        ],
      },
      {
        step_order: 4,
        scene_code: 'tita_procrastinacao',
        title: 'A Batalha contra o Titã da Procrastinação',
        narrative_text: 'O chão treme quando emerge o colosso: o Titã da Procrastinação! Uma criatura colossal feita de relógios parados, cobertores pesados e teias de aranha. Ele atira raios de cansaço que tentam colocá-lo para dormir para sempre!',
        scene_icon: '🗿',
        is_final_scene: false,
        actions: [
          {
            action_number: 1,
            title: 'Atacar com sequência de golpes rápidos antes que ele erga os braços',
            attribute_code: 'agi',
            difficulty_dc: 14,
            success_text: 'Sua velocidade impressionante atinge os pontos vitais do titã antes que ele reaja! Ele tomba de joelhos!',
            failure_text: 'O titã desce uma mão pesada como pedra sobre o seu escudo, afundando você na rocha (-18 HP)!',
            failure_damage: 18,
            bonus_gold: 15,
          },
          {
            action_number: 2,
            title: 'Alvejar a engrenagem central do peito com precisão letal',
            attribute_code: 'int',
            difficulty_dc: 14,
            success_text: 'Você identifica a mola-mestra do monstro e desfere um golpe fatal, fazendo o colosso desmoronar!',
            failure_text: 'O colosso dispara uma onda de areia estagnada que fustiga sua pele dolorosamente (-18 HP)!',
            failure_damage: 18,
            bonus_gold: 16,
          },
          {
            action_number: 3,
            title: 'Aparar o impacto do golpe do gigante com resistência suprema',
            attribute_code: 'con',
            difficulty_dc: 15,
            success_text: 'Como uma fortaleza viva, você não recua nenhum milímetro e contra-ataca derrubando o colosso!',
            failure_text: 'O impacto colossal quebra sua postura e atira você contra os pilares do salão (-18 HP)!',
            failure_damage: 18,
            bonus_gold: 14,
          },
        ],
      },
      {
        step_order: 5,
        scene_code: 'bau_tempo_conquistado',
        title: 'O Cofre do Tempo Conquistado',
        narrative_text: 'O titã desmancha em areia dourada e os relógios voltam a funcionar harmoniosamente! Diante de você ergue-se o Baú Dourado da Vitória Suprema, lacrado com engrenagens de ouro maciço.',
        scene_icon: '🏆',
        is_final_scene: true,
        actions: [
          {
            action_number: 1,
            title: 'Sincronizar as três engrenagens mestre no segundo exato',
            attribute_code: 'int',
            difficulty_dc: 13,
            success_text: 'Perfeição matemática! O baú explode em confetes de luz dourada e fanfarras reais!',
            failure_text: 'O mecanismo dá um recuo na sua mão, mas a trava se rompe revelando o ouro (-12 HP)!',
            failure_damage: 12,
            bonus_gold: 25,
          },
          {
            action_number: 2,
            title: 'Girar a chave mestra com destreza impecável',
            attribute_code: 'agi',
            difficulty_dc: 13,
            success_text: 'Suas mãos firmes abrem a fechadura em um milésimo de segundo sem nenhum atrito!',
            failure_text: 'A mola mestre arranha seu punho, mas a tampa voa revelando o tesouro imperial (-12 HP)!',
            failure_damage: 12,
            bonus_gold: 22,
          },
          {
            action_number: 3,
            title: 'Reclamar o tesouro em nome da vitória da disciplina familiar',
            attribute_code: 'cha',
            difficulty_dc: 14,
            success_text: 'A voz de quem venceu a procrastinação faz o cofre se abrir em reverência épica!',
            failure_text: 'A glória é conquistada com sangue e suor, celebrando o triunfo definitivo (-12 HP)!',
            failure_damage: 12,
            bonus_gold: 24,
          },
        ],
      },
    ],
  },
];

async function seed() {
  try {
    console.log('🌱 Populando catálogo de Masmorras e Livros-Jogos (Aventuras em Quest)...');

    for (const advData of ADVENTURES) {
      // 1. Criar ou atualizar aventura
      let adventure = await FamilyDungeonAdventure.findOne({ where: { code: advData.code } });
      if (!adventure) {
        adventure = await FamilyDungeonAdventure.create({
          id: randomUUID().toLowerCase(),
          code: advData.code,
          title: advData.title,
          description: advData.description,
          cover_icon: advData.cover_icon,
          difficulty_level: advData.difficulty_level,
          energy_cost: advData.energy_cost,
          base_gold_reward: advData.base_gold_reward,
          base_xp_reward: advData.base_xp_reward,
          is_active: true,
        });
        console.log(`  📜 Aventura criada: "${advData.title}"`);
      } else {
        await adventure.update({
          title: advData.title,
          description: advData.description,
          cover_icon: advData.cover_icon,
          difficulty_level: advData.difficulty_level,
          energy_cost: advData.energy_cost,
          base_gold_reward: advData.base_gold_reward,
          base_xp_reward: advData.base_xp_reward,
          is_active: true,
        });
        console.log(`  🔄 Aventura atualizada: "${advData.title}"`);
      }

      // 2. Criar ou atualizar cenas
      for (const scnData of advData.scenes) {
        let scene = await FamilyDungeonScene.findOne({
          where: { adventure_id: adventure.id, scene_code: scnData.scene_code },
        });

        if (!scene) {
          scene = await FamilyDungeonScene.create({
            id: randomUUID().toLowerCase(),
            adventure_id: adventure.id,
            step_order: scnData.step_order,
            scene_code: scnData.scene_code,
            title: scnData.title,
            narrative_text: scnData.narrative_text,
            scene_icon: scnData.scene_icon,
            is_final_scene: scnData.is_final_scene,
          });
        } else {
          await scene.update({
            step_order: scnData.step_order,
            title: scnData.title,
            narrative_text: scnData.narrative_text,
            scene_icon: scnData.scene_icon,
            is_final_scene: scnData.is_final_scene,
          });
        }

        // 3. Criar ou atualizar as 3 ações
        for (const actData of scnData.actions) {
          let action = await FamilyDungeonAction.findOne({
            where: { scene_id: scene.id, action_number: actData.action_number },
          });

          if (!action) {
            await FamilyDungeonAction.create({
              id: randomUUID().toLowerCase(),
              scene_id: scene.id,
              action_number: actData.action_number,
              title: actData.title,
              attribute_code: actData.attribute_code,
              difficulty_dc: actData.difficulty_dc,
              success_text: actData.success_text,
              failure_text: actData.failure_text,
              failure_damage: actData.failure_damage,
              bonus_gold: actData.bonus_gold,
            });
          } else {
            await action.update({
              title: actData.title,
              attribute_code: actData.attribute_code,
              difficulty_dc: actData.difficulty_dc,
              success_text: actData.success_text,
              failure_text: actData.failure_text,
              failure_damage: actData.failure_damage,
              bonus_gold: actData.bonus_gold,
            });
          }
        }
      }
    }

    console.log('🎉 Todas as 3 Masmorras e suas 15 cenas com 45 ações foram populadas com sucesso!');
    process.exit(0);
  } catch (err) {
    console.error('❌ Erro ao popular masmorras:', err);
    process.exit(1);
  }
}

seed();
